
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DefaultTag` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model DefaultTag
 * 
 */
export type DefaultTagModel = runtime.Types.Result.DefaultSelection<Prisma.$DefaultTagPayload>

export type AggregateDefaultTag = {
  _count: DefaultTagCountAggregateOutputType | null
  _avg: DefaultTagAvgAggregateOutputType | null
  _sum: DefaultTagSumAggregateOutputType | null
  _min: DefaultTagMinAggregateOutputType | null
  _max: DefaultTagMaxAggregateOutputType | null
}

export type DefaultTagAvgAggregateOutputType = {
  id: number | null
  tagId: number | null
}

export type DefaultTagSumAggregateOutputType = {
  id: number | null
  tagId: bigint | null
}

export type DefaultTagMinAggregateOutputType = {
  id: number | null
  tagId: bigint | null
}

export type DefaultTagMaxAggregateOutputType = {
  id: number | null
  tagId: bigint | null
}

export type DefaultTagCountAggregateOutputType = {
  id: number
  tagId: number
  _all: number
}


export type DefaultTagAvgAggregateInputType = {
  id?: true
  tagId?: true
}

export type DefaultTagSumAggregateInputType = {
  id?: true
  tagId?: true
}

export type DefaultTagMinAggregateInputType = {
  id?: true
  tagId?: true
}

export type DefaultTagMaxAggregateInputType = {
  id?: true
  tagId?: true
}

export type DefaultTagCountAggregateInputType = {
  id?: true
  tagId?: true
  _all?: true
}

export type DefaultTagAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DefaultTag to aggregate.
   */
  where?: Prisma.DefaultTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DefaultTags to fetch.
   */
  orderBy?: Prisma.DefaultTagOrderByWithRelationInput | Prisma.DefaultTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DefaultTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DefaultTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DefaultTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DefaultTags
  **/
  _count?: true | DefaultTagCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DefaultTagAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DefaultTagSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DefaultTagMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DefaultTagMaxAggregateInputType
}

export type GetDefaultTagAggregateType<T extends DefaultTagAggregateArgs> = {
      [P in keyof T & keyof AggregateDefaultTag]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDefaultTag[P]>
    : Prisma.GetScalarType<T[P], AggregateDefaultTag[P]>
}




export type DefaultTagGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DefaultTagWhereInput
  orderBy?: Prisma.DefaultTagOrderByWithAggregationInput | Prisma.DefaultTagOrderByWithAggregationInput[]
  by: Prisma.DefaultTagScalarFieldEnum[] | Prisma.DefaultTagScalarFieldEnum
  having?: Prisma.DefaultTagScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DefaultTagCountAggregateInputType | true
  _avg?: DefaultTagAvgAggregateInputType
  _sum?: DefaultTagSumAggregateInputType
  _min?: DefaultTagMinAggregateInputType
  _max?: DefaultTagMaxAggregateInputType
}

export type DefaultTagGroupByOutputType = {
  id: number
  tagId: bigint
  _count: DefaultTagCountAggregateOutputType | null
  _avg: DefaultTagAvgAggregateOutputType | null
  _sum: DefaultTagSumAggregateOutputType | null
  _min: DefaultTagMinAggregateOutputType | null
  _max: DefaultTagMaxAggregateOutputType | null
}

type GetDefaultTagGroupByPayload<T extends DefaultTagGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DefaultTagGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DefaultTagGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DefaultTagGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DefaultTagGroupByOutputType[P]>
      }
    >
  >



export type DefaultTagWhereInput = {
  AND?: Prisma.DefaultTagWhereInput | Prisma.DefaultTagWhereInput[]
  OR?: Prisma.DefaultTagWhereInput[]
  NOT?: Prisma.DefaultTagWhereInput | Prisma.DefaultTagWhereInput[]
  id?: Prisma.IntFilter<"DefaultTag"> | number
  tagId?: Prisma.BigIntFilter<"DefaultTag"> | bigint | number
  tag?: Prisma.XOR<Prisma.TagScalarRelationFilter, Prisma.TagWhereInput>
}

export type DefaultTagOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  tag?: Prisma.TagOrderByWithRelationInput
}

export type DefaultTagWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  tagId?: bigint | number
  AND?: Prisma.DefaultTagWhereInput | Prisma.DefaultTagWhereInput[]
  OR?: Prisma.DefaultTagWhereInput[]
  NOT?: Prisma.DefaultTagWhereInput | Prisma.DefaultTagWhereInput[]
  tag?: Prisma.XOR<Prisma.TagScalarRelationFilter, Prisma.TagWhereInput>
}, "id" | "tagId">

export type DefaultTagOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  _count?: Prisma.DefaultTagCountOrderByAggregateInput
  _avg?: Prisma.DefaultTagAvgOrderByAggregateInput
  _max?: Prisma.DefaultTagMaxOrderByAggregateInput
  _min?: Prisma.DefaultTagMinOrderByAggregateInput
  _sum?: Prisma.DefaultTagSumOrderByAggregateInput
}

export type DefaultTagScalarWhereWithAggregatesInput = {
  AND?: Prisma.DefaultTagScalarWhereWithAggregatesInput | Prisma.DefaultTagScalarWhereWithAggregatesInput[]
  OR?: Prisma.DefaultTagScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DefaultTagScalarWhereWithAggregatesInput | Prisma.DefaultTagScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"DefaultTag"> | number
  tagId?: Prisma.BigIntWithAggregatesFilter<"DefaultTag"> | bigint | number
}

export type DefaultTagCreateInput = {
  tag: Prisma.TagCreateNestedOneWithoutDefaultTagInput
}

export type DefaultTagUncheckedCreateInput = {
  id?: number
  tagId: bigint | number
}

export type DefaultTagUpdateInput = {
  tag?: Prisma.TagUpdateOneRequiredWithoutDefaultTagNestedInput
}

export type DefaultTagUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tagId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type DefaultTagCreateManyInput = {
  id?: number
  tagId: bigint | number
}

export type DefaultTagUpdateManyMutationInput = {

}

export type DefaultTagUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tagId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type DefaultTagNullableScalarRelationFilter = {
  is?: Prisma.DefaultTagWhereInput | null
  isNot?: Prisma.DefaultTagWhereInput | null
}

export type DefaultTagCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type DefaultTagAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type DefaultTagMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type DefaultTagMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type DefaultTagSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type DefaultTagCreateNestedOneWithoutTagInput = {
  create?: Prisma.XOR<Prisma.DefaultTagCreateWithoutTagInput, Prisma.DefaultTagUncheckedCreateWithoutTagInput>
  connectOrCreate?: Prisma.DefaultTagCreateOrConnectWithoutTagInput
  connect?: Prisma.DefaultTagWhereUniqueInput
}

export type DefaultTagUncheckedCreateNestedOneWithoutTagInput = {
  create?: Prisma.XOR<Prisma.DefaultTagCreateWithoutTagInput, Prisma.DefaultTagUncheckedCreateWithoutTagInput>
  connectOrCreate?: Prisma.DefaultTagCreateOrConnectWithoutTagInput
  connect?: Prisma.DefaultTagWhereUniqueInput
}

export type DefaultTagUpdateOneWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.DefaultTagCreateWithoutTagInput, Prisma.DefaultTagUncheckedCreateWithoutTagInput>
  connectOrCreate?: Prisma.DefaultTagCreateOrConnectWithoutTagInput
  upsert?: Prisma.DefaultTagUpsertWithoutTagInput
  disconnect?: Prisma.DefaultTagWhereInput | boolean
  delete?: Prisma.DefaultTagWhereInput | boolean
  connect?: Prisma.DefaultTagWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DefaultTagUpdateToOneWithWhereWithoutTagInput, Prisma.DefaultTagUpdateWithoutTagInput>, Prisma.DefaultTagUncheckedUpdateWithoutTagInput>
}

export type DefaultTagUncheckedUpdateOneWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.DefaultTagCreateWithoutTagInput, Prisma.DefaultTagUncheckedCreateWithoutTagInput>
  connectOrCreate?: Prisma.DefaultTagCreateOrConnectWithoutTagInput
  upsert?: Prisma.DefaultTagUpsertWithoutTagInput
  disconnect?: Prisma.DefaultTagWhereInput | boolean
  delete?: Prisma.DefaultTagWhereInput | boolean
  connect?: Prisma.DefaultTagWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DefaultTagUpdateToOneWithWhereWithoutTagInput, Prisma.DefaultTagUpdateWithoutTagInput>, Prisma.DefaultTagUncheckedUpdateWithoutTagInput>
}

export type DefaultTagCreateWithoutTagInput = {

}

export type DefaultTagUncheckedCreateWithoutTagInput = {
  id?: number
}

export type DefaultTagCreateOrConnectWithoutTagInput = {
  where: Prisma.DefaultTagWhereUniqueInput
  create: Prisma.XOR<Prisma.DefaultTagCreateWithoutTagInput, Prisma.DefaultTagUncheckedCreateWithoutTagInput>
}

export type DefaultTagUpsertWithoutTagInput = {
  update: Prisma.XOR<Prisma.DefaultTagUpdateWithoutTagInput, Prisma.DefaultTagUncheckedUpdateWithoutTagInput>
  create: Prisma.XOR<Prisma.DefaultTagCreateWithoutTagInput, Prisma.DefaultTagUncheckedCreateWithoutTagInput>
  where?: Prisma.DefaultTagWhereInput
}

export type DefaultTagUpdateToOneWithWhereWithoutTagInput = {
  where?: Prisma.DefaultTagWhereInput
  data: Prisma.XOR<Prisma.DefaultTagUpdateWithoutTagInput, Prisma.DefaultTagUncheckedUpdateWithoutTagInput>
}

export type DefaultTagUpdateWithoutTagInput = {

}

export type DefaultTagUncheckedUpdateWithoutTagInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
}



export type DefaultTagSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tagId?: boolean
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["defaultTag"]>



export type DefaultTagSelectScalar = {
  id?: boolean
  tagId?: boolean
}

export type DefaultTagOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tagId", ExtArgs["result"]["defaultTag"]>
export type DefaultTagInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}

export type $DefaultTagPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DefaultTag"
  objects: {
    tag: Prisma.$TagPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    tagId: bigint
  }, ExtArgs["result"]["defaultTag"]>
  composites: {}
}

export type DefaultTagGetPayload<S extends boolean | null | undefined | DefaultTagDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DefaultTagPayload, S>

export type DefaultTagCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DefaultTagFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DefaultTagCountAggregateInputType | true
  }

export interface DefaultTagDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DefaultTag'], meta: { name: 'DefaultTag' } }
  /**
   * Find zero or one DefaultTag that matches the filter.
   * @param {DefaultTagFindUniqueArgs} args - Arguments to find a DefaultTag
   * @example
   * // Get one DefaultTag
   * const defaultTag = await prisma.defaultTag.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DefaultTagFindUniqueArgs>(args: Prisma.SelectSubset<T, DefaultTagFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DefaultTagClient<runtime.Types.Result.GetResult<Prisma.$DefaultTagPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DefaultTag that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DefaultTagFindUniqueOrThrowArgs} args - Arguments to find a DefaultTag
   * @example
   * // Get one DefaultTag
   * const defaultTag = await prisma.defaultTag.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DefaultTagFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DefaultTagFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DefaultTagClient<runtime.Types.Result.GetResult<Prisma.$DefaultTagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DefaultTag that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DefaultTagFindFirstArgs} args - Arguments to find a DefaultTag
   * @example
   * // Get one DefaultTag
   * const defaultTag = await prisma.defaultTag.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DefaultTagFindFirstArgs>(args?: Prisma.SelectSubset<T, DefaultTagFindFirstArgs<ExtArgs>>): Prisma.Prisma__DefaultTagClient<runtime.Types.Result.GetResult<Prisma.$DefaultTagPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DefaultTag that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DefaultTagFindFirstOrThrowArgs} args - Arguments to find a DefaultTag
   * @example
   * // Get one DefaultTag
   * const defaultTag = await prisma.defaultTag.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DefaultTagFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DefaultTagFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DefaultTagClient<runtime.Types.Result.GetResult<Prisma.$DefaultTagPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DefaultTags that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DefaultTagFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DefaultTags
   * const defaultTags = await prisma.defaultTag.findMany()
   * 
   * // Get first 10 DefaultTags
   * const defaultTags = await prisma.defaultTag.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const defaultTagWithIdOnly = await prisma.defaultTag.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DefaultTagFindManyArgs>(args?: Prisma.SelectSubset<T, DefaultTagFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DefaultTagPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DefaultTag.
   * @param {DefaultTagCreateArgs} args - Arguments to create a DefaultTag.
   * @example
   * // Create one DefaultTag
   * const DefaultTag = await prisma.defaultTag.create({
   *   data: {
   *     // ... data to create a DefaultTag
   *   }
   * })
   * 
   */
  create<T extends DefaultTagCreateArgs>(args: Prisma.SelectSubset<T, DefaultTagCreateArgs<ExtArgs>>): Prisma.Prisma__DefaultTagClient<runtime.Types.Result.GetResult<Prisma.$DefaultTagPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DefaultTags.
   * @param {DefaultTagCreateManyArgs} args - Arguments to create many DefaultTags.
   * @example
   * // Create many DefaultTags
   * const defaultTag = await prisma.defaultTag.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DefaultTagCreateManyArgs>(args?: Prisma.SelectSubset<T, DefaultTagCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a DefaultTag.
   * @param {DefaultTagDeleteArgs} args - Arguments to delete one DefaultTag.
   * @example
   * // Delete one DefaultTag
   * const DefaultTag = await prisma.defaultTag.delete({
   *   where: {
   *     // ... filter to delete one DefaultTag
   *   }
   * })
   * 
   */
  delete<T extends DefaultTagDeleteArgs>(args: Prisma.SelectSubset<T, DefaultTagDeleteArgs<ExtArgs>>): Prisma.Prisma__DefaultTagClient<runtime.Types.Result.GetResult<Prisma.$DefaultTagPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DefaultTag.
   * @param {DefaultTagUpdateArgs} args - Arguments to update one DefaultTag.
   * @example
   * // Update one DefaultTag
   * const defaultTag = await prisma.defaultTag.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DefaultTagUpdateArgs>(args: Prisma.SelectSubset<T, DefaultTagUpdateArgs<ExtArgs>>): Prisma.Prisma__DefaultTagClient<runtime.Types.Result.GetResult<Prisma.$DefaultTagPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DefaultTags.
   * @param {DefaultTagDeleteManyArgs} args - Arguments to filter DefaultTags to delete.
   * @example
   * // Delete a few DefaultTags
   * const { count } = await prisma.defaultTag.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DefaultTagDeleteManyArgs>(args?: Prisma.SelectSubset<T, DefaultTagDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DefaultTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DefaultTagUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DefaultTags
   * const defaultTag = await prisma.defaultTag.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DefaultTagUpdateManyArgs>(args: Prisma.SelectSubset<T, DefaultTagUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one DefaultTag.
   * @param {DefaultTagUpsertArgs} args - Arguments to update or create a DefaultTag.
   * @example
   * // Update or create a DefaultTag
   * const defaultTag = await prisma.defaultTag.upsert({
   *   create: {
   *     // ... data to create a DefaultTag
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DefaultTag we want to update
   *   }
   * })
   */
  upsert<T extends DefaultTagUpsertArgs>(args: Prisma.SelectSubset<T, DefaultTagUpsertArgs<ExtArgs>>): Prisma.Prisma__DefaultTagClient<runtime.Types.Result.GetResult<Prisma.$DefaultTagPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DefaultTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DefaultTagCountArgs} args - Arguments to filter DefaultTags to count.
   * @example
   * // Count the number of DefaultTags
   * const count = await prisma.defaultTag.count({
   *   where: {
   *     // ... the filter for the DefaultTags we want to count
   *   }
   * })
  **/
  count<T extends DefaultTagCountArgs>(
    args?: Prisma.Subset<T, DefaultTagCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DefaultTagCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DefaultTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DefaultTagAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DefaultTagAggregateArgs>(args: Prisma.Subset<T, DefaultTagAggregateArgs>): Prisma.PrismaPromise<GetDefaultTagAggregateType<T>>

  /**
   * Group by DefaultTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DefaultTagGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DefaultTagGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DefaultTagGroupByArgs['orderBy'] }
      : { orderBy?: DefaultTagGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DefaultTagGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDefaultTagGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DefaultTag model
 */
readonly fields: DefaultTagFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DefaultTag.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DefaultTagClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tag<T extends Prisma.TagDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TagDefaultArgs<ExtArgs>>): Prisma.Prisma__TagClient<runtime.Types.Result.GetResult<Prisma.$TagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DefaultTag model
 */
export interface DefaultTagFieldRefs {
  readonly id: Prisma.FieldRef<"DefaultTag", 'Int'>
  readonly tagId: Prisma.FieldRef<"DefaultTag", 'BigInt'>
}
    

// Custom InputTypes
/**
 * DefaultTag findUnique
 */
export type DefaultTagFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DefaultTag
   */
  select?: Prisma.DefaultTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DefaultTag
   */
  omit?: Prisma.DefaultTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DefaultTagInclude<ExtArgs> | null
  /**
   * Filter, which DefaultTag to fetch.
   */
  where: Prisma.DefaultTagWhereUniqueInput
}

/**
 * DefaultTag findUniqueOrThrow
 */
export type DefaultTagFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DefaultTag
   */
  select?: Prisma.DefaultTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DefaultTag
   */
  omit?: Prisma.DefaultTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DefaultTagInclude<ExtArgs> | null
  /**
   * Filter, which DefaultTag to fetch.
   */
  where: Prisma.DefaultTagWhereUniqueInput
}

/**
 * DefaultTag findFirst
 */
export type DefaultTagFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DefaultTag
   */
  select?: Prisma.DefaultTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DefaultTag
   */
  omit?: Prisma.DefaultTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DefaultTagInclude<ExtArgs> | null
  /**
   * Filter, which DefaultTag to fetch.
   */
  where?: Prisma.DefaultTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DefaultTags to fetch.
   */
  orderBy?: Prisma.DefaultTagOrderByWithRelationInput | Prisma.DefaultTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DefaultTags.
   */
  cursor?: Prisma.DefaultTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DefaultTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DefaultTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DefaultTags.
   */
  distinct?: Prisma.DefaultTagScalarFieldEnum | Prisma.DefaultTagScalarFieldEnum[]
}

/**
 * DefaultTag findFirstOrThrow
 */
export type DefaultTagFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DefaultTag
   */
  select?: Prisma.DefaultTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DefaultTag
   */
  omit?: Prisma.DefaultTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DefaultTagInclude<ExtArgs> | null
  /**
   * Filter, which DefaultTag to fetch.
   */
  where?: Prisma.DefaultTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DefaultTags to fetch.
   */
  orderBy?: Prisma.DefaultTagOrderByWithRelationInput | Prisma.DefaultTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DefaultTags.
   */
  cursor?: Prisma.DefaultTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DefaultTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DefaultTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DefaultTags.
   */
  distinct?: Prisma.DefaultTagScalarFieldEnum | Prisma.DefaultTagScalarFieldEnum[]
}

/**
 * DefaultTag findMany
 */
export type DefaultTagFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DefaultTag
   */
  select?: Prisma.DefaultTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DefaultTag
   */
  omit?: Prisma.DefaultTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DefaultTagInclude<ExtArgs> | null
  /**
   * Filter, which DefaultTags to fetch.
   */
  where?: Prisma.DefaultTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DefaultTags to fetch.
   */
  orderBy?: Prisma.DefaultTagOrderByWithRelationInput | Prisma.DefaultTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DefaultTags.
   */
  cursor?: Prisma.DefaultTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DefaultTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DefaultTags.
   */
  skip?: number
  distinct?: Prisma.DefaultTagScalarFieldEnum | Prisma.DefaultTagScalarFieldEnum[]
}

/**
 * DefaultTag create
 */
export type DefaultTagCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DefaultTag
   */
  select?: Prisma.DefaultTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DefaultTag
   */
  omit?: Prisma.DefaultTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DefaultTagInclude<ExtArgs> | null
  /**
   * The data needed to create a DefaultTag.
   */
  data: Prisma.XOR<Prisma.DefaultTagCreateInput, Prisma.DefaultTagUncheckedCreateInput>
}

/**
 * DefaultTag createMany
 */
export type DefaultTagCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DefaultTags.
   */
  data: Prisma.DefaultTagCreateManyInput | Prisma.DefaultTagCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DefaultTag update
 */
export type DefaultTagUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DefaultTag
   */
  select?: Prisma.DefaultTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DefaultTag
   */
  omit?: Prisma.DefaultTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DefaultTagInclude<ExtArgs> | null
  /**
   * The data needed to update a DefaultTag.
   */
  data: Prisma.XOR<Prisma.DefaultTagUpdateInput, Prisma.DefaultTagUncheckedUpdateInput>
  /**
   * Choose, which DefaultTag to update.
   */
  where: Prisma.DefaultTagWhereUniqueInput
}

/**
 * DefaultTag updateMany
 */
export type DefaultTagUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DefaultTags.
   */
  data: Prisma.XOR<Prisma.DefaultTagUpdateManyMutationInput, Prisma.DefaultTagUncheckedUpdateManyInput>
  /**
   * Filter which DefaultTags to update
   */
  where?: Prisma.DefaultTagWhereInput
  /**
   * Limit how many DefaultTags to update.
   */
  limit?: number
}

/**
 * DefaultTag upsert
 */
export type DefaultTagUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DefaultTag
   */
  select?: Prisma.DefaultTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DefaultTag
   */
  omit?: Prisma.DefaultTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DefaultTagInclude<ExtArgs> | null
  /**
   * The filter to search for the DefaultTag to update in case it exists.
   */
  where: Prisma.DefaultTagWhereUniqueInput
  /**
   * In case the DefaultTag found by the `where` argument doesn't exist, create a new DefaultTag with this data.
   */
  create: Prisma.XOR<Prisma.DefaultTagCreateInput, Prisma.DefaultTagUncheckedCreateInput>
  /**
   * In case the DefaultTag was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DefaultTagUpdateInput, Prisma.DefaultTagUncheckedUpdateInput>
}

/**
 * DefaultTag delete
 */
export type DefaultTagDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DefaultTag
   */
  select?: Prisma.DefaultTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DefaultTag
   */
  omit?: Prisma.DefaultTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DefaultTagInclude<ExtArgs> | null
  /**
   * Filter which DefaultTag to delete.
   */
  where: Prisma.DefaultTagWhereUniqueInput
}

/**
 * DefaultTag deleteMany
 */
export type DefaultTagDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DefaultTags to delete
   */
  where?: Prisma.DefaultTagWhereInput
  /**
   * Limit how many DefaultTags to delete.
   */
  limit?: number
}

/**
 * DefaultTag without action
 */
export type DefaultTagDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DefaultTag
   */
  select?: Prisma.DefaultTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DefaultTag
   */
  omit?: Prisma.DefaultTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DefaultTagInclude<ExtArgs> | null
}
