
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LoginProviderCode` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model LoginProviderCode
 * 
 */
export type LoginProviderCodeModel = runtime.Types.Result.DefaultSelection<Prisma.$LoginProviderCodePayload>

export type AggregateLoginProviderCode = {
  _count: LoginProviderCodeCountAggregateOutputType | null
  _avg: LoginProviderCodeAvgAggregateOutputType | null
  _sum: LoginProviderCodeSumAggregateOutputType | null
  _min: LoginProviderCodeMinAggregateOutputType | null
  _max: LoginProviderCodeMaxAggregateOutputType | null
}

export type LoginProviderCodeAvgAggregateOutputType = {
  userId: number | null
  code: number | null
}

export type LoginProviderCodeSumAggregateOutputType = {
  userId: bigint | null
  code: bigint | null
}

export type LoginProviderCodeMinAggregateOutputType = {
  userId: bigint | null
  code: bigint | null
}

export type LoginProviderCodeMaxAggregateOutputType = {
  userId: bigint | null
  code: bigint | null
}

export type LoginProviderCodeCountAggregateOutputType = {
  userId: number
  code: number
  _all: number
}


export type LoginProviderCodeAvgAggregateInputType = {
  userId?: true
  code?: true
}

export type LoginProviderCodeSumAggregateInputType = {
  userId?: true
  code?: true
}

export type LoginProviderCodeMinAggregateInputType = {
  userId?: true
  code?: true
}

export type LoginProviderCodeMaxAggregateInputType = {
  userId?: true
  code?: true
}

export type LoginProviderCodeCountAggregateInputType = {
  userId?: true
  code?: true
  _all?: true
}

export type LoginProviderCodeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LoginProviderCode to aggregate.
   */
  where?: Prisma.LoginProviderCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoginProviderCodes to fetch.
   */
  orderBy?: Prisma.LoginProviderCodeOrderByWithRelationInput | Prisma.LoginProviderCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LoginProviderCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoginProviderCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoginProviderCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LoginProviderCodes
  **/
  _count?: true | LoginProviderCodeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LoginProviderCodeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LoginProviderCodeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LoginProviderCodeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LoginProviderCodeMaxAggregateInputType
}

export type GetLoginProviderCodeAggregateType<T extends LoginProviderCodeAggregateArgs> = {
      [P in keyof T & keyof AggregateLoginProviderCode]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLoginProviderCode[P]>
    : Prisma.GetScalarType<T[P], AggregateLoginProviderCode[P]>
}




export type LoginProviderCodeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LoginProviderCodeWhereInput
  orderBy?: Prisma.LoginProviderCodeOrderByWithAggregationInput | Prisma.LoginProviderCodeOrderByWithAggregationInput[]
  by: Prisma.LoginProviderCodeScalarFieldEnum[] | Prisma.LoginProviderCodeScalarFieldEnum
  having?: Prisma.LoginProviderCodeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LoginProviderCodeCountAggregateInputType | true
  _avg?: LoginProviderCodeAvgAggregateInputType
  _sum?: LoginProviderCodeSumAggregateInputType
  _min?: LoginProviderCodeMinAggregateInputType
  _max?: LoginProviderCodeMaxAggregateInputType
}

export type LoginProviderCodeGroupByOutputType = {
  userId: bigint
  code: bigint
  _count: LoginProviderCodeCountAggregateOutputType | null
  _avg: LoginProviderCodeAvgAggregateOutputType | null
  _sum: LoginProviderCodeSumAggregateOutputType | null
  _min: LoginProviderCodeMinAggregateOutputType | null
  _max: LoginProviderCodeMaxAggregateOutputType | null
}

type GetLoginProviderCodeGroupByPayload<T extends LoginProviderCodeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LoginProviderCodeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LoginProviderCodeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LoginProviderCodeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LoginProviderCodeGroupByOutputType[P]>
      }
    >
  >



export type LoginProviderCodeWhereInput = {
  AND?: Prisma.LoginProviderCodeWhereInput | Prisma.LoginProviderCodeWhereInput[]
  OR?: Prisma.LoginProviderCodeWhereInput[]
  NOT?: Prisma.LoginProviderCodeWhereInput | Prisma.LoginProviderCodeWhereInput[]
  userId?: Prisma.BigIntFilter<"LoginProviderCode"> | bigint | number
  code?: Prisma.BigIntFilter<"LoginProviderCode"> | bigint | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type LoginProviderCodeOrderByWithRelationInput = {
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type LoginProviderCodeWhereUniqueInput = Prisma.AtLeast<{
  userId?: bigint | number
  code?: bigint | number
  AND?: Prisma.LoginProviderCodeWhereInput | Prisma.LoginProviderCodeWhereInput[]
  OR?: Prisma.LoginProviderCodeWhereInput[]
  NOT?: Prisma.LoginProviderCodeWhereInput | Prisma.LoginProviderCodeWhereInput[]
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "userId" | "code">

export type LoginProviderCodeOrderByWithAggregationInput = {
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  _count?: Prisma.LoginProviderCodeCountOrderByAggregateInput
  _avg?: Prisma.LoginProviderCodeAvgOrderByAggregateInput
  _max?: Prisma.LoginProviderCodeMaxOrderByAggregateInput
  _min?: Prisma.LoginProviderCodeMinOrderByAggregateInput
  _sum?: Prisma.LoginProviderCodeSumOrderByAggregateInput
}

export type LoginProviderCodeScalarWhereWithAggregatesInput = {
  AND?: Prisma.LoginProviderCodeScalarWhereWithAggregatesInput | Prisma.LoginProviderCodeScalarWhereWithAggregatesInput[]
  OR?: Prisma.LoginProviderCodeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LoginProviderCodeScalarWhereWithAggregatesInput | Prisma.LoginProviderCodeScalarWhereWithAggregatesInput[]
  userId?: Prisma.BigIntWithAggregatesFilter<"LoginProviderCode"> | bigint | number
  code?: Prisma.BigIntWithAggregatesFilter<"LoginProviderCode"> | bigint | number
}

export type LoginProviderCodeCreateInput = {
  code: bigint | number
  user: Prisma.UserCreateNestedOneWithoutLoginProviderCodeInput
}

export type LoginProviderCodeUncheckedCreateInput = {
  userId: bigint | number
  code: bigint | number
}

export type LoginProviderCodeUpdateInput = {
  code?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  user?: Prisma.UserUpdateOneRequiredWithoutLoginProviderCodeNestedInput
}

export type LoginProviderCodeUncheckedUpdateInput = {
  userId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  code?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type LoginProviderCodeCreateManyInput = {
  userId: bigint | number
  code: bigint | number
}

export type LoginProviderCodeUpdateManyMutationInput = {
  code?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type LoginProviderCodeUncheckedUpdateManyInput = {
  userId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  code?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type LoginProviderCodeNullableScalarRelationFilter = {
  is?: Prisma.LoginProviderCodeWhereInput | null
  isNot?: Prisma.LoginProviderCodeWhereInput | null
}

export type LoginProviderCodeCountOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
}

export type LoginProviderCodeAvgOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
}

export type LoginProviderCodeMaxOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
}

export type LoginProviderCodeMinOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
}

export type LoginProviderCodeSumOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
}

export type LoginProviderCodeCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.LoginProviderCodeCreateWithoutUserInput, Prisma.LoginProviderCodeUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.LoginProviderCodeCreateOrConnectWithoutUserInput
  connect?: Prisma.LoginProviderCodeWhereUniqueInput
}

export type LoginProviderCodeUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.LoginProviderCodeCreateWithoutUserInput, Prisma.LoginProviderCodeUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.LoginProviderCodeCreateOrConnectWithoutUserInput
  connect?: Prisma.LoginProviderCodeWhereUniqueInput
}

export type LoginProviderCodeUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.LoginProviderCodeCreateWithoutUserInput, Prisma.LoginProviderCodeUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.LoginProviderCodeCreateOrConnectWithoutUserInput
  upsert?: Prisma.LoginProviderCodeUpsertWithoutUserInput
  disconnect?: Prisma.LoginProviderCodeWhereInput | boolean
  delete?: Prisma.LoginProviderCodeWhereInput | boolean
  connect?: Prisma.LoginProviderCodeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LoginProviderCodeUpdateToOneWithWhereWithoutUserInput, Prisma.LoginProviderCodeUpdateWithoutUserInput>, Prisma.LoginProviderCodeUncheckedUpdateWithoutUserInput>
}

export type LoginProviderCodeUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.LoginProviderCodeCreateWithoutUserInput, Prisma.LoginProviderCodeUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.LoginProviderCodeCreateOrConnectWithoutUserInput
  upsert?: Prisma.LoginProviderCodeUpsertWithoutUserInput
  disconnect?: Prisma.LoginProviderCodeWhereInput | boolean
  delete?: Prisma.LoginProviderCodeWhereInput | boolean
  connect?: Prisma.LoginProviderCodeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LoginProviderCodeUpdateToOneWithWhereWithoutUserInput, Prisma.LoginProviderCodeUpdateWithoutUserInput>, Prisma.LoginProviderCodeUncheckedUpdateWithoutUserInput>
}

export type LoginProviderCodeCreateWithoutUserInput = {
  code: bigint | number
}

export type LoginProviderCodeUncheckedCreateWithoutUserInput = {
  code: bigint | number
}

export type LoginProviderCodeCreateOrConnectWithoutUserInput = {
  where: Prisma.LoginProviderCodeWhereUniqueInput
  create: Prisma.XOR<Prisma.LoginProviderCodeCreateWithoutUserInput, Prisma.LoginProviderCodeUncheckedCreateWithoutUserInput>
}

export type LoginProviderCodeUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.LoginProviderCodeUpdateWithoutUserInput, Prisma.LoginProviderCodeUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.LoginProviderCodeCreateWithoutUserInput, Prisma.LoginProviderCodeUncheckedCreateWithoutUserInput>
  where?: Prisma.LoginProviderCodeWhereInput
}

export type LoginProviderCodeUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.LoginProviderCodeWhereInput
  data: Prisma.XOR<Prisma.LoginProviderCodeUpdateWithoutUserInput, Prisma.LoginProviderCodeUncheckedUpdateWithoutUserInput>
}

export type LoginProviderCodeUpdateWithoutUserInput = {
  code?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type LoginProviderCodeUncheckedUpdateWithoutUserInput = {
  code?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}



export type LoginProviderCodeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  code?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["loginProviderCode"]>



export type LoginProviderCodeSelectScalar = {
  userId?: boolean
  code?: boolean
}

export type LoginProviderCodeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"userId" | "code", ExtArgs["result"]["loginProviderCode"]>
export type LoginProviderCodeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $LoginProviderCodePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LoginProviderCode"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    userId: bigint
    code: bigint
  }, ExtArgs["result"]["loginProviderCode"]>
  composites: {}
}

export type LoginProviderCodeGetPayload<S extends boolean | null | undefined | LoginProviderCodeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LoginProviderCodePayload, S>

export type LoginProviderCodeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LoginProviderCodeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LoginProviderCodeCountAggregateInputType | true
  }

export interface LoginProviderCodeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LoginProviderCode'], meta: { name: 'LoginProviderCode' } }
  /**
   * Find zero or one LoginProviderCode that matches the filter.
   * @param {LoginProviderCodeFindUniqueArgs} args - Arguments to find a LoginProviderCode
   * @example
   * // Get one LoginProviderCode
   * const loginProviderCode = await prisma.loginProviderCode.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LoginProviderCodeFindUniqueArgs>(args: Prisma.SelectSubset<T, LoginProviderCodeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LoginProviderCodeClient<runtime.Types.Result.GetResult<Prisma.$LoginProviderCodePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LoginProviderCode that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LoginProviderCodeFindUniqueOrThrowArgs} args - Arguments to find a LoginProviderCode
   * @example
   * // Get one LoginProviderCode
   * const loginProviderCode = await prisma.loginProviderCode.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LoginProviderCodeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LoginProviderCodeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LoginProviderCodeClient<runtime.Types.Result.GetResult<Prisma.$LoginProviderCodePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LoginProviderCode that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoginProviderCodeFindFirstArgs} args - Arguments to find a LoginProviderCode
   * @example
   * // Get one LoginProviderCode
   * const loginProviderCode = await prisma.loginProviderCode.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LoginProviderCodeFindFirstArgs>(args?: Prisma.SelectSubset<T, LoginProviderCodeFindFirstArgs<ExtArgs>>): Prisma.Prisma__LoginProviderCodeClient<runtime.Types.Result.GetResult<Prisma.$LoginProviderCodePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LoginProviderCode that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoginProviderCodeFindFirstOrThrowArgs} args - Arguments to find a LoginProviderCode
   * @example
   * // Get one LoginProviderCode
   * const loginProviderCode = await prisma.loginProviderCode.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LoginProviderCodeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LoginProviderCodeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LoginProviderCodeClient<runtime.Types.Result.GetResult<Prisma.$LoginProviderCodePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LoginProviderCodes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoginProviderCodeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LoginProviderCodes
   * const loginProviderCodes = await prisma.loginProviderCode.findMany()
   * 
   * // Get first 10 LoginProviderCodes
   * const loginProviderCodes = await prisma.loginProviderCode.findMany({ take: 10 })
   * 
   * // Only select the `userId`
   * const loginProviderCodeWithUserIdOnly = await prisma.loginProviderCode.findMany({ select: { userId: true } })
   * 
   */
  findMany<T extends LoginProviderCodeFindManyArgs>(args?: Prisma.SelectSubset<T, LoginProviderCodeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LoginProviderCodePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LoginProviderCode.
   * @param {LoginProviderCodeCreateArgs} args - Arguments to create a LoginProviderCode.
   * @example
   * // Create one LoginProviderCode
   * const LoginProviderCode = await prisma.loginProviderCode.create({
   *   data: {
   *     // ... data to create a LoginProviderCode
   *   }
   * })
   * 
   */
  create<T extends LoginProviderCodeCreateArgs>(args: Prisma.SelectSubset<T, LoginProviderCodeCreateArgs<ExtArgs>>): Prisma.Prisma__LoginProviderCodeClient<runtime.Types.Result.GetResult<Prisma.$LoginProviderCodePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LoginProviderCodes.
   * @param {LoginProviderCodeCreateManyArgs} args - Arguments to create many LoginProviderCodes.
   * @example
   * // Create many LoginProviderCodes
   * const loginProviderCode = await prisma.loginProviderCode.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LoginProviderCodeCreateManyArgs>(args?: Prisma.SelectSubset<T, LoginProviderCodeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a LoginProviderCode.
   * @param {LoginProviderCodeDeleteArgs} args - Arguments to delete one LoginProviderCode.
   * @example
   * // Delete one LoginProviderCode
   * const LoginProviderCode = await prisma.loginProviderCode.delete({
   *   where: {
   *     // ... filter to delete one LoginProviderCode
   *   }
   * })
   * 
   */
  delete<T extends LoginProviderCodeDeleteArgs>(args: Prisma.SelectSubset<T, LoginProviderCodeDeleteArgs<ExtArgs>>): Prisma.Prisma__LoginProviderCodeClient<runtime.Types.Result.GetResult<Prisma.$LoginProviderCodePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LoginProviderCode.
   * @param {LoginProviderCodeUpdateArgs} args - Arguments to update one LoginProviderCode.
   * @example
   * // Update one LoginProviderCode
   * const loginProviderCode = await prisma.loginProviderCode.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LoginProviderCodeUpdateArgs>(args: Prisma.SelectSubset<T, LoginProviderCodeUpdateArgs<ExtArgs>>): Prisma.Prisma__LoginProviderCodeClient<runtime.Types.Result.GetResult<Prisma.$LoginProviderCodePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LoginProviderCodes.
   * @param {LoginProviderCodeDeleteManyArgs} args - Arguments to filter LoginProviderCodes to delete.
   * @example
   * // Delete a few LoginProviderCodes
   * const { count } = await prisma.loginProviderCode.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LoginProviderCodeDeleteManyArgs>(args?: Prisma.SelectSubset<T, LoginProviderCodeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LoginProviderCodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoginProviderCodeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LoginProviderCodes
   * const loginProviderCode = await prisma.loginProviderCode.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LoginProviderCodeUpdateManyArgs>(args: Prisma.SelectSubset<T, LoginProviderCodeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one LoginProviderCode.
   * @param {LoginProviderCodeUpsertArgs} args - Arguments to update or create a LoginProviderCode.
   * @example
   * // Update or create a LoginProviderCode
   * const loginProviderCode = await prisma.loginProviderCode.upsert({
   *   create: {
   *     // ... data to create a LoginProviderCode
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LoginProviderCode we want to update
   *   }
   * })
   */
  upsert<T extends LoginProviderCodeUpsertArgs>(args: Prisma.SelectSubset<T, LoginProviderCodeUpsertArgs<ExtArgs>>): Prisma.Prisma__LoginProviderCodeClient<runtime.Types.Result.GetResult<Prisma.$LoginProviderCodePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LoginProviderCodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoginProviderCodeCountArgs} args - Arguments to filter LoginProviderCodes to count.
   * @example
   * // Count the number of LoginProviderCodes
   * const count = await prisma.loginProviderCode.count({
   *   where: {
   *     // ... the filter for the LoginProviderCodes we want to count
   *   }
   * })
  **/
  count<T extends LoginProviderCodeCountArgs>(
    args?: Prisma.Subset<T, LoginProviderCodeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LoginProviderCodeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LoginProviderCode.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoginProviderCodeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LoginProviderCodeAggregateArgs>(args: Prisma.Subset<T, LoginProviderCodeAggregateArgs>): Prisma.PrismaPromise<GetLoginProviderCodeAggregateType<T>>

  /**
   * Group by LoginProviderCode.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoginProviderCodeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LoginProviderCodeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LoginProviderCodeGroupByArgs['orderBy'] }
      : { orderBy?: LoginProviderCodeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LoginProviderCodeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLoginProviderCodeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LoginProviderCode model
 */
readonly fields: LoginProviderCodeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LoginProviderCode.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LoginProviderCodeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LoginProviderCode model
 */
export interface LoginProviderCodeFieldRefs {
  readonly userId: Prisma.FieldRef<"LoginProviderCode", 'BigInt'>
  readonly code: Prisma.FieldRef<"LoginProviderCode", 'BigInt'>
}
    

// Custom InputTypes
/**
 * LoginProviderCode findUnique
 */
export type LoginProviderCodeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoginProviderCode
   */
  select?: Prisma.LoginProviderCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoginProviderCode
   */
  omit?: Prisma.LoginProviderCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoginProviderCodeInclude<ExtArgs> | null
  /**
   * Filter, which LoginProviderCode to fetch.
   */
  where: Prisma.LoginProviderCodeWhereUniqueInput
}

/**
 * LoginProviderCode findUniqueOrThrow
 */
export type LoginProviderCodeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoginProviderCode
   */
  select?: Prisma.LoginProviderCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoginProviderCode
   */
  omit?: Prisma.LoginProviderCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoginProviderCodeInclude<ExtArgs> | null
  /**
   * Filter, which LoginProviderCode to fetch.
   */
  where: Prisma.LoginProviderCodeWhereUniqueInput
}

/**
 * LoginProviderCode findFirst
 */
export type LoginProviderCodeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoginProviderCode
   */
  select?: Prisma.LoginProviderCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoginProviderCode
   */
  omit?: Prisma.LoginProviderCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoginProviderCodeInclude<ExtArgs> | null
  /**
   * Filter, which LoginProviderCode to fetch.
   */
  where?: Prisma.LoginProviderCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoginProviderCodes to fetch.
   */
  orderBy?: Prisma.LoginProviderCodeOrderByWithRelationInput | Prisma.LoginProviderCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LoginProviderCodes.
   */
  cursor?: Prisma.LoginProviderCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoginProviderCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoginProviderCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LoginProviderCodes.
   */
  distinct?: Prisma.LoginProviderCodeScalarFieldEnum | Prisma.LoginProviderCodeScalarFieldEnum[]
}

/**
 * LoginProviderCode findFirstOrThrow
 */
export type LoginProviderCodeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoginProviderCode
   */
  select?: Prisma.LoginProviderCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoginProviderCode
   */
  omit?: Prisma.LoginProviderCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoginProviderCodeInclude<ExtArgs> | null
  /**
   * Filter, which LoginProviderCode to fetch.
   */
  where?: Prisma.LoginProviderCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoginProviderCodes to fetch.
   */
  orderBy?: Prisma.LoginProviderCodeOrderByWithRelationInput | Prisma.LoginProviderCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LoginProviderCodes.
   */
  cursor?: Prisma.LoginProviderCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoginProviderCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoginProviderCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LoginProviderCodes.
   */
  distinct?: Prisma.LoginProviderCodeScalarFieldEnum | Prisma.LoginProviderCodeScalarFieldEnum[]
}

/**
 * LoginProviderCode findMany
 */
export type LoginProviderCodeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoginProviderCode
   */
  select?: Prisma.LoginProviderCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoginProviderCode
   */
  omit?: Prisma.LoginProviderCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoginProviderCodeInclude<ExtArgs> | null
  /**
   * Filter, which LoginProviderCodes to fetch.
   */
  where?: Prisma.LoginProviderCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoginProviderCodes to fetch.
   */
  orderBy?: Prisma.LoginProviderCodeOrderByWithRelationInput | Prisma.LoginProviderCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LoginProviderCodes.
   */
  cursor?: Prisma.LoginProviderCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoginProviderCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoginProviderCodes.
   */
  skip?: number
  distinct?: Prisma.LoginProviderCodeScalarFieldEnum | Prisma.LoginProviderCodeScalarFieldEnum[]
}

/**
 * LoginProviderCode create
 */
export type LoginProviderCodeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoginProviderCode
   */
  select?: Prisma.LoginProviderCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoginProviderCode
   */
  omit?: Prisma.LoginProviderCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoginProviderCodeInclude<ExtArgs> | null
  /**
   * The data needed to create a LoginProviderCode.
   */
  data: Prisma.XOR<Prisma.LoginProviderCodeCreateInput, Prisma.LoginProviderCodeUncheckedCreateInput>
}

/**
 * LoginProviderCode createMany
 */
export type LoginProviderCodeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LoginProviderCodes.
   */
  data: Prisma.LoginProviderCodeCreateManyInput | Prisma.LoginProviderCodeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LoginProviderCode update
 */
export type LoginProviderCodeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoginProviderCode
   */
  select?: Prisma.LoginProviderCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoginProviderCode
   */
  omit?: Prisma.LoginProviderCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoginProviderCodeInclude<ExtArgs> | null
  /**
   * The data needed to update a LoginProviderCode.
   */
  data: Prisma.XOR<Prisma.LoginProviderCodeUpdateInput, Prisma.LoginProviderCodeUncheckedUpdateInput>
  /**
   * Choose, which LoginProviderCode to update.
   */
  where: Prisma.LoginProviderCodeWhereUniqueInput
}

/**
 * LoginProviderCode updateMany
 */
export type LoginProviderCodeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LoginProviderCodes.
   */
  data: Prisma.XOR<Prisma.LoginProviderCodeUpdateManyMutationInput, Prisma.LoginProviderCodeUncheckedUpdateManyInput>
  /**
   * Filter which LoginProviderCodes to update
   */
  where?: Prisma.LoginProviderCodeWhereInput
  /**
   * Limit how many LoginProviderCodes to update.
   */
  limit?: number
}

/**
 * LoginProviderCode upsert
 */
export type LoginProviderCodeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoginProviderCode
   */
  select?: Prisma.LoginProviderCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoginProviderCode
   */
  omit?: Prisma.LoginProviderCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoginProviderCodeInclude<ExtArgs> | null
  /**
   * The filter to search for the LoginProviderCode to update in case it exists.
   */
  where: Prisma.LoginProviderCodeWhereUniqueInput
  /**
   * In case the LoginProviderCode found by the `where` argument doesn't exist, create a new LoginProviderCode with this data.
   */
  create: Prisma.XOR<Prisma.LoginProviderCodeCreateInput, Prisma.LoginProviderCodeUncheckedCreateInput>
  /**
   * In case the LoginProviderCode was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LoginProviderCodeUpdateInput, Prisma.LoginProviderCodeUncheckedUpdateInput>
}

/**
 * LoginProviderCode delete
 */
export type LoginProviderCodeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoginProviderCode
   */
  select?: Prisma.LoginProviderCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoginProviderCode
   */
  omit?: Prisma.LoginProviderCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoginProviderCodeInclude<ExtArgs> | null
  /**
   * Filter which LoginProviderCode to delete.
   */
  where: Prisma.LoginProviderCodeWhereUniqueInput
}

/**
 * LoginProviderCode deleteMany
 */
export type LoginProviderCodeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LoginProviderCodes to delete
   */
  where?: Prisma.LoginProviderCodeWhereInput
  /**
   * Limit how many LoginProviderCodes to delete.
   */
  limit?: number
}

/**
 * LoginProviderCode without action
 */
export type LoginProviderCodeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoginProviderCode
   */
  select?: Prisma.LoginProviderCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoginProviderCode
   */
  omit?: Prisma.LoginProviderCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoginProviderCodeInclude<ExtArgs> | null
}
