
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ParticipantMark` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ParticipantMark
 * 
 */
export type ParticipantMarkModel = runtime.Types.Result.DefaultSelection<Prisma.$ParticipantMarkPayload>

export type AggregateParticipantMark = {
  _count: ParticipantMarkCountAggregateOutputType | null
  _avg: ParticipantMarkAvgAggregateOutputType | null
  _sum: ParticipantMarkSumAggregateOutputType | null
  _min: ParticipantMarkMinAggregateOutputType | null
  _max: ParticipantMarkMaxAggregateOutputType | null
}

export type ParticipantMarkAvgAggregateOutputType = {
  participantId: number | null
  tagId: number | null
}

export type ParticipantMarkSumAggregateOutputType = {
  participantId: number | null
  tagId: number | null
}

export type ParticipantMarkMinAggregateOutputType = {
  participantId: number | null
  tagId: number | null
  calendarDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ParticipantMarkMaxAggregateOutputType = {
  participantId: number | null
  tagId: number | null
  calendarDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ParticipantMarkCountAggregateOutputType = {
  participantId: number
  tagId: number
  calendarDate: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ParticipantMarkAvgAggregateInputType = {
  participantId?: true
  tagId?: true
}

export type ParticipantMarkSumAggregateInputType = {
  participantId?: true
  tagId?: true
}

export type ParticipantMarkMinAggregateInputType = {
  participantId?: true
  tagId?: true
  calendarDate?: true
  createdAt?: true
  updatedAt?: true
}

export type ParticipantMarkMaxAggregateInputType = {
  participantId?: true
  tagId?: true
  calendarDate?: true
  createdAt?: true
  updatedAt?: true
}

export type ParticipantMarkCountAggregateInputType = {
  participantId?: true
  tagId?: true
  calendarDate?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ParticipantMarkAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ParticipantMark to aggregate.
   */
  where?: Prisma.ParticipantMarkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ParticipantMarks to fetch.
   */
  orderBy?: Prisma.ParticipantMarkOrderByWithRelationInput | Prisma.ParticipantMarkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ParticipantMarkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ParticipantMarks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ParticipantMarks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ParticipantMarks
  **/
  _count?: true | ParticipantMarkCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ParticipantMarkAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ParticipantMarkSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ParticipantMarkMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ParticipantMarkMaxAggregateInputType
}

export type GetParticipantMarkAggregateType<T extends ParticipantMarkAggregateArgs> = {
      [P in keyof T & keyof AggregateParticipantMark]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateParticipantMark[P]>
    : Prisma.GetScalarType<T[P], AggregateParticipantMark[P]>
}




export type ParticipantMarkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ParticipantMarkWhereInput
  orderBy?: Prisma.ParticipantMarkOrderByWithAggregationInput | Prisma.ParticipantMarkOrderByWithAggregationInput[]
  by: Prisma.ParticipantMarkScalarFieldEnum[] | Prisma.ParticipantMarkScalarFieldEnum
  having?: Prisma.ParticipantMarkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ParticipantMarkCountAggregateInputType | true
  _avg?: ParticipantMarkAvgAggregateInputType
  _sum?: ParticipantMarkSumAggregateInputType
  _min?: ParticipantMarkMinAggregateInputType
  _max?: ParticipantMarkMaxAggregateInputType
}

export type ParticipantMarkGroupByOutputType = {
  participantId: number
  tagId: number
  calendarDate: Date
  createdAt: Date
  updatedAt: Date
  _count: ParticipantMarkCountAggregateOutputType | null
  _avg: ParticipantMarkAvgAggregateOutputType | null
  _sum: ParticipantMarkSumAggregateOutputType | null
  _min: ParticipantMarkMinAggregateOutputType | null
  _max: ParticipantMarkMaxAggregateOutputType | null
}

type GetParticipantMarkGroupByPayload<T extends ParticipantMarkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ParticipantMarkGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ParticipantMarkGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ParticipantMarkGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ParticipantMarkGroupByOutputType[P]>
      }
    >
  >



export type ParticipantMarkWhereInput = {
  AND?: Prisma.ParticipantMarkWhereInput | Prisma.ParticipantMarkWhereInput[]
  OR?: Prisma.ParticipantMarkWhereInput[]
  NOT?: Prisma.ParticipantMarkWhereInput | Prisma.ParticipantMarkWhereInput[]
  participantId?: Prisma.IntFilter<"ParticipantMark"> | number
  tagId?: Prisma.IntFilter<"ParticipantMark"> | number
  calendarDate?: Prisma.DateTimeFilter<"ParticipantMark"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"ParticipantMark"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ParticipantMark"> | Date | string
  participant?: Prisma.XOR<Prisma.ParticipantScalarRelationFilter, Prisma.ParticipantWhereInput>
  tag?: Prisma.XOR<Prisma.TagScalarRelationFilter, Prisma.TagWhereInput>
}

export type ParticipantMarkOrderByWithRelationInput = {
  participantId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  calendarDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  participant?: Prisma.ParticipantOrderByWithRelationInput
  tag?: Prisma.TagOrderByWithRelationInput
}

export type ParticipantMarkWhereUniqueInput = Prisma.AtLeast<{
  participantId_tagId_calendarDate?: Prisma.ParticipantMarkParticipantIdTagIdCalendarDateCompoundUniqueInput
  AND?: Prisma.ParticipantMarkWhereInput | Prisma.ParticipantMarkWhereInput[]
  OR?: Prisma.ParticipantMarkWhereInput[]
  NOT?: Prisma.ParticipantMarkWhereInput | Prisma.ParticipantMarkWhereInput[]
  participantId?: Prisma.IntFilter<"ParticipantMark"> | number
  tagId?: Prisma.IntFilter<"ParticipantMark"> | number
  calendarDate?: Prisma.DateTimeFilter<"ParticipantMark"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"ParticipantMark"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ParticipantMark"> | Date | string
  participant?: Prisma.XOR<Prisma.ParticipantScalarRelationFilter, Prisma.ParticipantWhereInput>
  tag?: Prisma.XOR<Prisma.TagScalarRelationFilter, Prisma.TagWhereInput>
}, "participantId_tagId_calendarDate">

export type ParticipantMarkOrderByWithAggregationInput = {
  participantId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  calendarDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ParticipantMarkCountOrderByAggregateInput
  _avg?: Prisma.ParticipantMarkAvgOrderByAggregateInput
  _max?: Prisma.ParticipantMarkMaxOrderByAggregateInput
  _min?: Prisma.ParticipantMarkMinOrderByAggregateInput
  _sum?: Prisma.ParticipantMarkSumOrderByAggregateInput
}

export type ParticipantMarkScalarWhereWithAggregatesInput = {
  AND?: Prisma.ParticipantMarkScalarWhereWithAggregatesInput | Prisma.ParticipantMarkScalarWhereWithAggregatesInput[]
  OR?: Prisma.ParticipantMarkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ParticipantMarkScalarWhereWithAggregatesInput | Prisma.ParticipantMarkScalarWhereWithAggregatesInput[]
  participantId?: Prisma.IntWithAggregatesFilter<"ParticipantMark"> | number
  tagId?: Prisma.IntWithAggregatesFilter<"ParticipantMark"> | number
  calendarDate?: Prisma.DateTimeWithAggregatesFilter<"ParticipantMark"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ParticipantMark"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ParticipantMark"> | Date | string
}

export type ParticipantMarkCreateInput = {
  calendarDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  participant: Prisma.ParticipantCreateNestedOneWithoutParticipantMarksInput
  tag: Prisma.TagCreateNestedOneWithoutParticipantMarksInput
}

export type ParticipantMarkUncheckedCreateInput = {
  participantId: number
  tagId: number
  calendarDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ParticipantMarkUpdateInput = {
  calendarDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  participant?: Prisma.ParticipantUpdateOneRequiredWithoutParticipantMarksNestedInput
  tag?: Prisma.TagUpdateOneRequiredWithoutParticipantMarksNestedInput
}

export type ParticipantMarkUncheckedUpdateInput = {
  participantId?: Prisma.IntFieldUpdateOperationsInput | number
  tagId?: Prisma.IntFieldUpdateOperationsInput | number
  calendarDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ParticipantMarkCreateManyInput = {
  participantId: number
  tagId: number
  calendarDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ParticipantMarkUpdateManyMutationInput = {
  calendarDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ParticipantMarkUncheckedUpdateManyInput = {
  participantId?: Prisma.IntFieldUpdateOperationsInput | number
  tagId?: Prisma.IntFieldUpdateOperationsInput | number
  calendarDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ParticipantMarkListRelationFilter = {
  every?: Prisma.ParticipantMarkWhereInput
  some?: Prisma.ParticipantMarkWhereInput
  none?: Prisma.ParticipantMarkWhereInput
}

export type ParticipantMarkOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ParticipantMarkParticipantIdTagIdCalendarDateCompoundUniqueInput = {
  participantId: number
  tagId: number
  calendarDate: Date | string
}

export type ParticipantMarkCountOrderByAggregateInput = {
  participantId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  calendarDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ParticipantMarkAvgOrderByAggregateInput = {
  participantId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type ParticipantMarkMaxOrderByAggregateInput = {
  participantId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  calendarDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ParticipantMarkMinOrderByAggregateInput = {
  participantId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  calendarDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ParticipantMarkSumOrderByAggregateInput = {
  participantId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type ParticipantMarkCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.ParticipantMarkCreateWithoutTagInput, Prisma.ParticipantMarkUncheckedCreateWithoutTagInput> | Prisma.ParticipantMarkCreateWithoutTagInput[] | Prisma.ParticipantMarkUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.ParticipantMarkCreateOrConnectWithoutTagInput | Prisma.ParticipantMarkCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.ParticipantMarkCreateManyTagInputEnvelope
  connect?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
}

export type ParticipantMarkUncheckedCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.ParticipantMarkCreateWithoutTagInput, Prisma.ParticipantMarkUncheckedCreateWithoutTagInput> | Prisma.ParticipantMarkCreateWithoutTagInput[] | Prisma.ParticipantMarkUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.ParticipantMarkCreateOrConnectWithoutTagInput | Prisma.ParticipantMarkCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.ParticipantMarkCreateManyTagInputEnvelope
  connect?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
}

export type ParticipantMarkUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.ParticipantMarkCreateWithoutTagInput, Prisma.ParticipantMarkUncheckedCreateWithoutTagInput> | Prisma.ParticipantMarkCreateWithoutTagInput[] | Prisma.ParticipantMarkUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.ParticipantMarkCreateOrConnectWithoutTagInput | Prisma.ParticipantMarkCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.ParticipantMarkUpsertWithWhereUniqueWithoutTagInput | Prisma.ParticipantMarkUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.ParticipantMarkCreateManyTagInputEnvelope
  set?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
  disconnect?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
  delete?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
  connect?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
  update?: Prisma.ParticipantMarkUpdateWithWhereUniqueWithoutTagInput | Prisma.ParticipantMarkUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.ParticipantMarkUpdateManyWithWhereWithoutTagInput | Prisma.ParticipantMarkUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.ParticipantMarkScalarWhereInput | Prisma.ParticipantMarkScalarWhereInput[]
}

export type ParticipantMarkUncheckedUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.ParticipantMarkCreateWithoutTagInput, Prisma.ParticipantMarkUncheckedCreateWithoutTagInput> | Prisma.ParticipantMarkCreateWithoutTagInput[] | Prisma.ParticipantMarkUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.ParticipantMarkCreateOrConnectWithoutTagInput | Prisma.ParticipantMarkCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.ParticipantMarkUpsertWithWhereUniqueWithoutTagInput | Prisma.ParticipantMarkUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.ParticipantMarkCreateManyTagInputEnvelope
  set?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
  disconnect?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
  delete?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
  connect?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
  update?: Prisma.ParticipantMarkUpdateWithWhereUniqueWithoutTagInput | Prisma.ParticipantMarkUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.ParticipantMarkUpdateManyWithWhereWithoutTagInput | Prisma.ParticipantMarkUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.ParticipantMarkScalarWhereInput | Prisma.ParticipantMarkScalarWhereInput[]
}

export type ParticipantMarkCreateNestedManyWithoutParticipantInput = {
  create?: Prisma.XOR<Prisma.ParticipantMarkCreateWithoutParticipantInput, Prisma.ParticipantMarkUncheckedCreateWithoutParticipantInput> | Prisma.ParticipantMarkCreateWithoutParticipantInput[] | Prisma.ParticipantMarkUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.ParticipantMarkCreateOrConnectWithoutParticipantInput | Prisma.ParticipantMarkCreateOrConnectWithoutParticipantInput[]
  createMany?: Prisma.ParticipantMarkCreateManyParticipantInputEnvelope
  connect?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
}

export type ParticipantMarkUncheckedCreateNestedManyWithoutParticipantInput = {
  create?: Prisma.XOR<Prisma.ParticipantMarkCreateWithoutParticipantInput, Prisma.ParticipantMarkUncheckedCreateWithoutParticipantInput> | Prisma.ParticipantMarkCreateWithoutParticipantInput[] | Prisma.ParticipantMarkUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.ParticipantMarkCreateOrConnectWithoutParticipantInput | Prisma.ParticipantMarkCreateOrConnectWithoutParticipantInput[]
  createMany?: Prisma.ParticipantMarkCreateManyParticipantInputEnvelope
  connect?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
}

export type ParticipantMarkUpdateManyWithoutParticipantNestedInput = {
  create?: Prisma.XOR<Prisma.ParticipantMarkCreateWithoutParticipantInput, Prisma.ParticipantMarkUncheckedCreateWithoutParticipantInput> | Prisma.ParticipantMarkCreateWithoutParticipantInput[] | Prisma.ParticipantMarkUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.ParticipantMarkCreateOrConnectWithoutParticipantInput | Prisma.ParticipantMarkCreateOrConnectWithoutParticipantInput[]
  upsert?: Prisma.ParticipantMarkUpsertWithWhereUniqueWithoutParticipantInput | Prisma.ParticipantMarkUpsertWithWhereUniqueWithoutParticipantInput[]
  createMany?: Prisma.ParticipantMarkCreateManyParticipantInputEnvelope
  set?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
  disconnect?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
  delete?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
  connect?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
  update?: Prisma.ParticipantMarkUpdateWithWhereUniqueWithoutParticipantInput | Prisma.ParticipantMarkUpdateWithWhereUniqueWithoutParticipantInput[]
  updateMany?: Prisma.ParticipantMarkUpdateManyWithWhereWithoutParticipantInput | Prisma.ParticipantMarkUpdateManyWithWhereWithoutParticipantInput[]
  deleteMany?: Prisma.ParticipantMarkScalarWhereInput | Prisma.ParticipantMarkScalarWhereInput[]
}

export type ParticipantMarkUncheckedUpdateManyWithoutParticipantNestedInput = {
  create?: Prisma.XOR<Prisma.ParticipantMarkCreateWithoutParticipantInput, Prisma.ParticipantMarkUncheckedCreateWithoutParticipantInput> | Prisma.ParticipantMarkCreateWithoutParticipantInput[] | Prisma.ParticipantMarkUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.ParticipantMarkCreateOrConnectWithoutParticipantInput | Prisma.ParticipantMarkCreateOrConnectWithoutParticipantInput[]
  upsert?: Prisma.ParticipantMarkUpsertWithWhereUniqueWithoutParticipantInput | Prisma.ParticipantMarkUpsertWithWhereUniqueWithoutParticipantInput[]
  createMany?: Prisma.ParticipantMarkCreateManyParticipantInputEnvelope
  set?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
  disconnect?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
  delete?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
  connect?: Prisma.ParticipantMarkWhereUniqueInput | Prisma.ParticipantMarkWhereUniqueInput[]
  update?: Prisma.ParticipantMarkUpdateWithWhereUniqueWithoutParticipantInput | Prisma.ParticipantMarkUpdateWithWhereUniqueWithoutParticipantInput[]
  updateMany?: Prisma.ParticipantMarkUpdateManyWithWhereWithoutParticipantInput | Prisma.ParticipantMarkUpdateManyWithWhereWithoutParticipantInput[]
  deleteMany?: Prisma.ParticipantMarkScalarWhereInput | Prisma.ParticipantMarkScalarWhereInput[]
}

export type ParticipantMarkCreateWithoutTagInput = {
  calendarDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  participant: Prisma.ParticipantCreateNestedOneWithoutParticipantMarksInput
}

export type ParticipantMarkUncheckedCreateWithoutTagInput = {
  participantId: number
  calendarDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ParticipantMarkCreateOrConnectWithoutTagInput = {
  where: Prisma.ParticipantMarkWhereUniqueInput
  create: Prisma.XOR<Prisma.ParticipantMarkCreateWithoutTagInput, Prisma.ParticipantMarkUncheckedCreateWithoutTagInput>
}

export type ParticipantMarkCreateManyTagInputEnvelope = {
  data: Prisma.ParticipantMarkCreateManyTagInput | Prisma.ParticipantMarkCreateManyTagInput[]
  skipDuplicates?: boolean
}

export type ParticipantMarkUpsertWithWhereUniqueWithoutTagInput = {
  where: Prisma.ParticipantMarkWhereUniqueInput
  update: Prisma.XOR<Prisma.ParticipantMarkUpdateWithoutTagInput, Prisma.ParticipantMarkUncheckedUpdateWithoutTagInput>
  create: Prisma.XOR<Prisma.ParticipantMarkCreateWithoutTagInput, Prisma.ParticipantMarkUncheckedCreateWithoutTagInput>
}

export type ParticipantMarkUpdateWithWhereUniqueWithoutTagInput = {
  where: Prisma.ParticipantMarkWhereUniqueInput
  data: Prisma.XOR<Prisma.ParticipantMarkUpdateWithoutTagInput, Prisma.ParticipantMarkUncheckedUpdateWithoutTagInput>
}

export type ParticipantMarkUpdateManyWithWhereWithoutTagInput = {
  where: Prisma.ParticipantMarkScalarWhereInput
  data: Prisma.XOR<Prisma.ParticipantMarkUpdateManyMutationInput, Prisma.ParticipantMarkUncheckedUpdateManyWithoutTagInput>
}

export type ParticipantMarkScalarWhereInput = {
  AND?: Prisma.ParticipantMarkScalarWhereInput | Prisma.ParticipantMarkScalarWhereInput[]
  OR?: Prisma.ParticipantMarkScalarWhereInput[]
  NOT?: Prisma.ParticipantMarkScalarWhereInput | Prisma.ParticipantMarkScalarWhereInput[]
  participantId?: Prisma.IntFilter<"ParticipantMark"> | number
  tagId?: Prisma.IntFilter<"ParticipantMark"> | number
  calendarDate?: Prisma.DateTimeFilter<"ParticipantMark"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"ParticipantMark"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ParticipantMark"> | Date | string
}

export type ParticipantMarkCreateWithoutParticipantInput = {
  calendarDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  tag: Prisma.TagCreateNestedOneWithoutParticipantMarksInput
}

export type ParticipantMarkUncheckedCreateWithoutParticipantInput = {
  tagId: number
  calendarDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ParticipantMarkCreateOrConnectWithoutParticipantInput = {
  where: Prisma.ParticipantMarkWhereUniqueInput
  create: Prisma.XOR<Prisma.ParticipantMarkCreateWithoutParticipantInput, Prisma.ParticipantMarkUncheckedCreateWithoutParticipantInput>
}

export type ParticipantMarkCreateManyParticipantInputEnvelope = {
  data: Prisma.ParticipantMarkCreateManyParticipantInput | Prisma.ParticipantMarkCreateManyParticipantInput[]
  skipDuplicates?: boolean
}

export type ParticipantMarkUpsertWithWhereUniqueWithoutParticipantInput = {
  where: Prisma.ParticipantMarkWhereUniqueInput
  update: Prisma.XOR<Prisma.ParticipantMarkUpdateWithoutParticipantInput, Prisma.ParticipantMarkUncheckedUpdateWithoutParticipantInput>
  create: Prisma.XOR<Prisma.ParticipantMarkCreateWithoutParticipantInput, Prisma.ParticipantMarkUncheckedCreateWithoutParticipantInput>
}

export type ParticipantMarkUpdateWithWhereUniqueWithoutParticipantInput = {
  where: Prisma.ParticipantMarkWhereUniqueInput
  data: Prisma.XOR<Prisma.ParticipantMarkUpdateWithoutParticipantInput, Prisma.ParticipantMarkUncheckedUpdateWithoutParticipantInput>
}

export type ParticipantMarkUpdateManyWithWhereWithoutParticipantInput = {
  where: Prisma.ParticipantMarkScalarWhereInput
  data: Prisma.XOR<Prisma.ParticipantMarkUpdateManyMutationInput, Prisma.ParticipantMarkUncheckedUpdateManyWithoutParticipantInput>
}

export type ParticipantMarkCreateManyTagInput = {
  participantId: number
  calendarDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ParticipantMarkUpdateWithoutTagInput = {
  calendarDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  participant?: Prisma.ParticipantUpdateOneRequiredWithoutParticipantMarksNestedInput
}

export type ParticipantMarkUncheckedUpdateWithoutTagInput = {
  participantId?: Prisma.IntFieldUpdateOperationsInput | number
  calendarDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ParticipantMarkUncheckedUpdateManyWithoutTagInput = {
  participantId?: Prisma.IntFieldUpdateOperationsInput | number
  calendarDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ParticipantMarkCreateManyParticipantInput = {
  tagId: number
  calendarDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ParticipantMarkUpdateWithoutParticipantInput = {
  calendarDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tag?: Prisma.TagUpdateOneRequiredWithoutParticipantMarksNestedInput
}

export type ParticipantMarkUncheckedUpdateWithoutParticipantInput = {
  tagId?: Prisma.IntFieldUpdateOperationsInput | number
  calendarDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ParticipantMarkUncheckedUpdateManyWithoutParticipantInput = {
  tagId?: Prisma.IntFieldUpdateOperationsInput | number
  calendarDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ParticipantMarkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  participantId?: boolean
  tagId?: boolean
  calendarDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  participant?: boolean | Prisma.ParticipantDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["participantMark"]>



export type ParticipantMarkSelectScalar = {
  participantId?: boolean
  tagId?: boolean
  calendarDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ParticipantMarkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"participantId" | "tagId" | "calendarDate" | "createdAt" | "updatedAt", ExtArgs["result"]["participantMark"]>
export type ParticipantMarkInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participant?: boolean | Prisma.ParticipantDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}

export type $ParticipantMarkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ParticipantMark"
  objects: {
    participant: Prisma.$ParticipantPayload<ExtArgs>
    tag: Prisma.$TagPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    participantId: number
    tagId: number
    calendarDate: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["participantMark"]>
  composites: {}
}

export type ParticipantMarkGetPayload<S extends boolean | null | undefined | ParticipantMarkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ParticipantMarkPayload, S>

export type ParticipantMarkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ParticipantMarkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ParticipantMarkCountAggregateInputType | true
  }

export interface ParticipantMarkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ParticipantMark'], meta: { name: 'ParticipantMark' } }
  /**
   * Find zero or one ParticipantMark that matches the filter.
   * @param {ParticipantMarkFindUniqueArgs} args - Arguments to find a ParticipantMark
   * @example
   * // Get one ParticipantMark
   * const participantMark = await prisma.participantMark.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ParticipantMarkFindUniqueArgs>(args: Prisma.SelectSubset<T, ParticipantMarkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ParticipantMarkClient<runtime.Types.Result.GetResult<Prisma.$ParticipantMarkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ParticipantMark that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ParticipantMarkFindUniqueOrThrowArgs} args - Arguments to find a ParticipantMark
   * @example
   * // Get one ParticipantMark
   * const participantMark = await prisma.participantMark.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ParticipantMarkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ParticipantMarkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ParticipantMarkClient<runtime.Types.Result.GetResult<Prisma.$ParticipantMarkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ParticipantMark that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipantMarkFindFirstArgs} args - Arguments to find a ParticipantMark
   * @example
   * // Get one ParticipantMark
   * const participantMark = await prisma.participantMark.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ParticipantMarkFindFirstArgs>(args?: Prisma.SelectSubset<T, ParticipantMarkFindFirstArgs<ExtArgs>>): Prisma.Prisma__ParticipantMarkClient<runtime.Types.Result.GetResult<Prisma.$ParticipantMarkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ParticipantMark that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipantMarkFindFirstOrThrowArgs} args - Arguments to find a ParticipantMark
   * @example
   * // Get one ParticipantMark
   * const participantMark = await prisma.participantMark.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ParticipantMarkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ParticipantMarkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ParticipantMarkClient<runtime.Types.Result.GetResult<Prisma.$ParticipantMarkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ParticipantMarks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipantMarkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ParticipantMarks
   * const participantMarks = await prisma.participantMark.findMany()
   * 
   * // Get first 10 ParticipantMarks
   * const participantMarks = await prisma.participantMark.findMany({ take: 10 })
   * 
   * // Only select the `participantId`
   * const participantMarkWithParticipantIdOnly = await prisma.participantMark.findMany({ select: { participantId: true } })
   * 
   */
  findMany<T extends ParticipantMarkFindManyArgs>(args?: Prisma.SelectSubset<T, ParticipantMarkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ParticipantMarkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ParticipantMark.
   * @param {ParticipantMarkCreateArgs} args - Arguments to create a ParticipantMark.
   * @example
   * // Create one ParticipantMark
   * const ParticipantMark = await prisma.participantMark.create({
   *   data: {
   *     // ... data to create a ParticipantMark
   *   }
   * })
   * 
   */
  create<T extends ParticipantMarkCreateArgs>(args: Prisma.SelectSubset<T, ParticipantMarkCreateArgs<ExtArgs>>): Prisma.Prisma__ParticipantMarkClient<runtime.Types.Result.GetResult<Prisma.$ParticipantMarkPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ParticipantMarks.
   * @param {ParticipantMarkCreateManyArgs} args - Arguments to create many ParticipantMarks.
   * @example
   * // Create many ParticipantMarks
   * const participantMark = await prisma.participantMark.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ParticipantMarkCreateManyArgs>(args?: Prisma.SelectSubset<T, ParticipantMarkCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ParticipantMark.
   * @param {ParticipantMarkDeleteArgs} args - Arguments to delete one ParticipantMark.
   * @example
   * // Delete one ParticipantMark
   * const ParticipantMark = await prisma.participantMark.delete({
   *   where: {
   *     // ... filter to delete one ParticipantMark
   *   }
   * })
   * 
   */
  delete<T extends ParticipantMarkDeleteArgs>(args: Prisma.SelectSubset<T, ParticipantMarkDeleteArgs<ExtArgs>>): Prisma.Prisma__ParticipantMarkClient<runtime.Types.Result.GetResult<Prisma.$ParticipantMarkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ParticipantMark.
   * @param {ParticipantMarkUpdateArgs} args - Arguments to update one ParticipantMark.
   * @example
   * // Update one ParticipantMark
   * const participantMark = await prisma.participantMark.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ParticipantMarkUpdateArgs>(args: Prisma.SelectSubset<T, ParticipantMarkUpdateArgs<ExtArgs>>): Prisma.Prisma__ParticipantMarkClient<runtime.Types.Result.GetResult<Prisma.$ParticipantMarkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ParticipantMarks.
   * @param {ParticipantMarkDeleteManyArgs} args - Arguments to filter ParticipantMarks to delete.
   * @example
   * // Delete a few ParticipantMarks
   * const { count } = await prisma.participantMark.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ParticipantMarkDeleteManyArgs>(args?: Prisma.SelectSubset<T, ParticipantMarkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ParticipantMarks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipantMarkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ParticipantMarks
   * const participantMark = await prisma.participantMark.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ParticipantMarkUpdateManyArgs>(args: Prisma.SelectSubset<T, ParticipantMarkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ParticipantMark.
   * @param {ParticipantMarkUpsertArgs} args - Arguments to update or create a ParticipantMark.
   * @example
   * // Update or create a ParticipantMark
   * const participantMark = await prisma.participantMark.upsert({
   *   create: {
   *     // ... data to create a ParticipantMark
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ParticipantMark we want to update
   *   }
   * })
   */
  upsert<T extends ParticipantMarkUpsertArgs>(args: Prisma.SelectSubset<T, ParticipantMarkUpsertArgs<ExtArgs>>): Prisma.Prisma__ParticipantMarkClient<runtime.Types.Result.GetResult<Prisma.$ParticipantMarkPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ParticipantMarks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipantMarkCountArgs} args - Arguments to filter ParticipantMarks to count.
   * @example
   * // Count the number of ParticipantMarks
   * const count = await prisma.participantMark.count({
   *   where: {
   *     // ... the filter for the ParticipantMarks we want to count
   *   }
   * })
  **/
  count<T extends ParticipantMarkCountArgs>(
    args?: Prisma.Subset<T, ParticipantMarkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ParticipantMarkCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ParticipantMark.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipantMarkAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ParticipantMarkAggregateArgs>(args: Prisma.Subset<T, ParticipantMarkAggregateArgs>): Prisma.PrismaPromise<GetParticipantMarkAggregateType<T>>

  /**
   * Group by ParticipantMark.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipantMarkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ParticipantMarkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ParticipantMarkGroupByArgs['orderBy'] }
      : { orderBy?: ParticipantMarkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ParticipantMarkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetParticipantMarkGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ParticipantMark model
 */
readonly fields: ParticipantMarkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ParticipantMark.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ParticipantMarkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  participant<T extends Prisma.ParticipantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ParticipantDefaultArgs<ExtArgs>>): Prisma.Prisma__ParticipantClient<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  tag<T extends Prisma.TagDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TagDefaultArgs<ExtArgs>>): Prisma.Prisma__TagClient<runtime.Types.Result.GetResult<Prisma.$TagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ParticipantMark model
 */
export interface ParticipantMarkFieldRefs {
  readonly participantId: Prisma.FieldRef<"ParticipantMark", 'Int'>
  readonly tagId: Prisma.FieldRef<"ParticipantMark", 'Int'>
  readonly calendarDate: Prisma.FieldRef<"ParticipantMark", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"ParticipantMark", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ParticipantMark", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ParticipantMark findUnique
 */
export type ParticipantMarkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParticipantMark
   */
  select?: Prisma.ParticipantMarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParticipantMark
   */
  omit?: Prisma.ParticipantMarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantMarkInclude<ExtArgs> | null
  /**
   * Filter, which ParticipantMark to fetch.
   */
  where: Prisma.ParticipantMarkWhereUniqueInput
}

/**
 * ParticipantMark findUniqueOrThrow
 */
export type ParticipantMarkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParticipantMark
   */
  select?: Prisma.ParticipantMarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParticipantMark
   */
  omit?: Prisma.ParticipantMarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantMarkInclude<ExtArgs> | null
  /**
   * Filter, which ParticipantMark to fetch.
   */
  where: Prisma.ParticipantMarkWhereUniqueInput
}

/**
 * ParticipantMark findFirst
 */
export type ParticipantMarkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParticipantMark
   */
  select?: Prisma.ParticipantMarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParticipantMark
   */
  omit?: Prisma.ParticipantMarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantMarkInclude<ExtArgs> | null
  /**
   * Filter, which ParticipantMark to fetch.
   */
  where?: Prisma.ParticipantMarkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ParticipantMarks to fetch.
   */
  orderBy?: Prisma.ParticipantMarkOrderByWithRelationInput | Prisma.ParticipantMarkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ParticipantMarks.
   */
  cursor?: Prisma.ParticipantMarkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ParticipantMarks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ParticipantMarks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ParticipantMarks.
   */
  distinct?: Prisma.ParticipantMarkScalarFieldEnum | Prisma.ParticipantMarkScalarFieldEnum[]
}

/**
 * ParticipantMark findFirstOrThrow
 */
export type ParticipantMarkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParticipantMark
   */
  select?: Prisma.ParticipantMarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParticipantMark
   */
  omit?: Prisma.ParticipantMarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantMarkInclude<ExtArgs> | null
  /**
   * Filter, which ParticipantMark to fetch.
   */
  where?: Prisma.ParticipantMarkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ParticipantMarks to fetch.
   */
  orderBy?: Prisma.ParticipantMarkOrderByWithRelationInput | Prisma.ParticipantMarkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ParticipantMarks.
   */
  cursor?: Prisma.ParticipantMarkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ParticipantMarks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ParticipantMarks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ParticipantMarks.
   */
  distinct?: Prisma.ParticipantMarkScalarFieldEnum | Prisma.ParticipantMarkScalarFieldEnum[]
}

/**
 * ParticipantMark findMany
 */
export type ParticipantMarkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParticipantMark
   */
  select?: Prisma.ParticipantMarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParticipantMark
   */
  omit?: Prisma.ParticipantMarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantMarkInclude<ExtArgs> | null
  /**
   * Filter, which ParticipantMarks to fetch.
   */
  where?: Prisma.ParticipantMarkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ParticipantMarks to fetch.
   */
  orderBy?: Prisma.ParticipantMarkOrderByWithRelationInput | Prisma.ParticipantMarkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ParticipantMarks.
   */
  cursor?: Prisma.ParticipantMarkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ParticipantMarks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ParticipantMarks.
   */
  skip?: number
  distinct?: Prisma.ParticipantMarkScalarFieldEnum | Prisma.ParticipantMarkScalarFieldEnum[]
}

/**
 * ParticipantMark create
 */
export type ParticipantMarkCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParticipantMark
   */
  select?: Prisma.ParticipantMarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParticipantMark
   */
  omit?: Prisma.ParticipantMarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantMarkInclude<ExtArgs> | null
  /**
   * The data needed to create a ParticipantMark.
   */
  data: Prisma.XOR<Prisma.ParticipantMarkCreateInput, Prisma.ParticipantMarkUncheckedCreateInput>
}

/**
 * ParticipantMark createMany
 */
export type ParticipantMarkCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ParticipantMarks.
   */
  data: Prisma.ParticipantMarkCreateManyInput | Prisma.ParticipantMarkCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ParticipantMark update
 */
export type ParticipantMarkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParticipantMark
   */
  select?: Prisma.ParticipantMarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParticipantMark
   */
  omit?: Prisma.ParticipantMarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantMarkInclude<ExtArgs> | null
  /**
   * The data needed to update a ParticipantMark.
   */
  data: Prisma.XOR<Prisma.ParticipantMarkUpdateInput, Prisma.ParticipantMarkUncheckedUpdateInput>
  /**
   * Choose, which ParticipantMark to update.
   */
  where: Prisma.ParticipantMarkWhereUniqueInput
}

/**
 * ParticipantMark updateMany
 */
export type ParticipantMarkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ParticipantMarks.
   */
  data: Prisma.XOR<Prisma.ParticipantMarkUpdateManyMutationInput, Prisma.ParticipantMarkUncheckedUpdateManyInput>
  /**
   * Filter which ParticipantMarks to update
   */
  where?: Prisma.ParticipantMarkWhereInput
  /**
   * Limit how many ParticipantMarks to update.
   */
  limit?: number
}

/**
 * ParticipantMark upsert
 */
export type ParticipantMarkUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParticipantMark
   */
  select?: Prisma.ParticipantMarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParticipantMark
   */
  omit?: Prisma.ParticipantMarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantMarkInclude<ExtArgs> | null
  /**
   * The filter to search for the ParticipantMark to update in case it exists.
   */
  where: Prisma.ParticipantMarkWhereUniqueInput
  /**
   * In case the ParticipantMark found by the `where` argument doesn't exist, create a new ParticipantMark with this data.
   */
  create: Prisma.XOR<Prisma.ParticipantMarkCreateInput, Prisma.ParticipantMarkUncheckedCreateInput>
  /**
   * In case the ParticipantMark was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ParticipantMarkUpdateInput, Prisma.ParticipantMarkUncheckedUpdateInput>
}

/**
 * ParticipantMark delete
 */
export type ParticipantMarkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParticipantMark
   */
  select?: Prisma.ParticipantMarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParticipantMark
   */
  omit?: Prisma.ParticipantMarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantMarkInclude<ExtArgs> | null
  /**
   * Filter which ParticipantMark to delete.
   */
  where: Prisma.ParticipantMarkWhereUniqueInput
}

/**
 * ParticipantMark deleteMany
 */
export type ParticipantMarkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ParticipantMarks to delete
   */
  where?: Prisma.ParticipantMarkWhereInput
  /**
   * Limit how many ParticipantMarks to delete.
   */
  limit?: number
}

/**
 * ParticipantMark without action
 */
export type ParticipantMarkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParticipantMark
   */
  select?: Prisma.ParticipantMarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParticipantMark
   */
  omit?: Prisma.ParticipantMarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantMarkInclude<ExtArgs> | null
}
