
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TagsOnAppointments` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model TagsOnAppointments
 * 
 */
export type TagsOnAppointmentsModel = runtime.Types.Result.DefaultSelection<Prisma.$TagsOnAppointmentsPayload>

export type AggregateTagsOnAppointments = {
  _count: TagsOnAppointmentsCountAggregateOutputType | null
  _avg: TagsOnAppointmentsAvgAggregateOutputType | null
  _sum: TagsOnAppointmentsSumAggregateOutputType | null
  _min: TagsOnAppointmentsMinAggregateOutputType | null
  _max: TagsOnAppointmentsMaxAggregateOutputType | null
}

export type TagsOnAppointmentsAvgAggregateOutputType = {
  appointmentId: number | null
  tagId: number | null
}

export type TagsOnAppointmentsSumAggregateOutputType = {
  appointmentId: number | null
  tagId: number | null
}

export type TagsOnAppointmentsMinAggregateOutputType = {
  appointmentId: number | null
  tagId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TagsOnAppointmentsMaxAggregateOutputType = {
  appointmentId: number | null
  tagId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TagsOnAppointmentsCountAggregateOutputType = {
  appointmentId: number
  tagId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TagsOnAppointmentsAvgAggregateInputType = {
  appointmentId?: true
  tagId?: true
}

export type TagsOnAppointmentsSumAggregateInputType = {
  appointmentId?: true
  tagId?: true
}

export type TagsOnAppointmentsMinAggregateInputType = {
  appointmentId?: true
  tagId?: true
  createdAt?: true
  updatedAt?: true
}

export type TagsOnAppointmentsMaxAggregateInputType = {
  appointmentId?: true
  tagId?: true
  createdAt?: true
  updatedAt?: true
}

export type TagsOnAppointmentsCountAggregateInputType = {
  appointmentId?: true
  tagId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TagsOnAppointmentsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TagsOnAppointments to aggregate.
   */
  where?: Prisma.TagsOnAppointmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagsOnAppointments to fetch.
   */
  orderBy?: Prisma.TagsOnAppointmentsOrderByWithRelationInput | Prisma.TagsOnAppointmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TagsOnAppointmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagsOnAppointments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagsOnAppointments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TagsOnAppointments
  **/
  _count?: true | TagsOnAppointmentsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TagsOnAppointmentsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TagsOnAppointmentsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TagsOnAppointmentsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TagsOnAppointmentsMaxAggregateInputType
}

export type GetTagsOnAppointmentsAggregateType<T extends TagsOnAppointmentsAggregateArgs> = {
      [P in keyof T & keyof AggregateTagsOnAppointments]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTagsOnAppointments[P]>
    : Prisma.GetScalarType<T[P], AggregateTagsOnAppointments[P]>
}




export type TagsOnAppointmentsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TagsOnAppointmentsWhereInput
  orderBy?: Prisma.TagsOnAppointmentsOrderByWithAggregationInput | Prisma.TagsOnAppointmentsOrderByWithAggregationInput[]
  by: Prisma.TagsOnAppointmentsScalarFieldEnum[] | Prisma.TagsOnAppointmentsScalarFieldEnum
  having?: Prisma.TagsOnAppointmentsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TagsOnAppointmentsCountAggregateInputType | true
  _avg?: TagsOnAppointmentsAvgAggregateInputType
  _sum?: TagsOnAppointmentsSumAggregateInputType
  _min?: TagsOnAppointmentsMinAggregateInputType
  _max?: TagsOnAppointmentsMaxAggregateInputType
}

export type TagsOnAppointmentsGroupByOutputType = {
  appointmentId: number
  tagId: number
  createdAt: Date
  updatedAt: Date
  _count: TagsOnAppointmentsCountAggregateOutputType | null
  _avg: TagsOnAppointmentsAvgAggregateOutputType | null
  _sum: TagsOnAppointmentsSumAggregateOutputType | null
  _min: TagsOnAppointmentsMinAggregateOutputType | null
  _max: TagsOnAppointmentsMaxAggregateOutputType | null
}

type GetTagsOnAppointmentsGroupByPayload<T extends TagsOnAppointmentsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TagsOnAppointmentsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TagsOnAppointmentsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TagsOnAppointmentsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TagsOnAppointmentsGroupByOutputType[P]>
      }
    >
  >



export type TagsOnAppointmentsWhereInput = {
  AND?: Prisma.TagsOnAppointmentsWhereInput | Prisma.TagsOnAppointmentsWhereInput[]
  OR?: Prisma.TagsOnAppointmentsWhereInput[]
  NOT?: Prisma.TagsOnAppointmentsWhereInput | Prisma.TagsOnAppointmentsWhereInput[]
  appointmentId?: Prisma.IntFilter<"TagsOnAppointments"> | number
  tagId?: Prisma.IntFilter<"TagsOnAppointments"> | number
  createdAt?: Prisma.DateTimeFilter<"TagsOnAppointments"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TagsOnAppointments"> | Date | string
  appointment?: Prisma.XOR<Prisma.AppointmentScalarRelationFilter, Prisma.AppointmentWhereInput>
  tag?: Prisma.XOR<Prisma.TagScalarRelationFilter, Prisma.TagWhereInput>
}

export type TagsOnAppointmentsOrderByWithRelationInput = {
  appointmentId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  appointment?: Prisma.AppointmentOrderByWithRelationInput
  tag?: Prisma.TagOrderByWithRelationInput
}

export type TagsOnAppointmentsWhereUniqueInput = Prisma.AtLeast<{
  appointmentId_tagId?: Prisma.TagsOnAppointmentsAppointmentIdTagIdCompoundUniqueInput
  AND?: Prisma.TagsOnAppointmentsWhereInput | Prisma.TagsOnAppointmentsWhereInput[]
  OR?: Prisma.TagsOnAppointmentsWhereInput[]
  NOT?: Prisma.TagsOnAppointmentsWhereInput | Prisma.TagsOnAppointmentsWhereInput[]
  appointmentId?: Prisma.IntFilter<"TagsOnAppointments"> | number
  tagId?: Prisma.IntFilter<"TagsOnAppointments"> | number
  createdAt?: Prisma.DateTimeFilter<"TagsOnAppointments"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TagsOnAppointments"> | Date | string
  appointment?: Prisma.XOR<Prisma.AppointmentScalarRelationFilter, Prisma.AppointmentWhereInput>
  tag?: Prisma.XOR<Prisma.TagScalarRelationFilter, Prisma.TagWhereInput>
}, "appointmentId_tagId">

export type TagsOnAppointmentsOrderByWithAggregationInput = {
  appointmentId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TagsOnAppointmentsCountOrderByAggregateInput
  _avg?: Prisma.TagsOnAppointmentsAvgOrderByAggregateInput
  _max?: Prisma.TagsOnAppointmentsMaxOrderByAggregateInput
  _min?: Prisma.TagsOnAppointmentsMinOrderByAggregateInput
  _sum?: Prisma.TagsOnAppointmentsSumOrderByAggregateInput
}

export type TagsOnAppointmentsScalarWhereWithAggregatesInput = {
  AND?: Prisma.TagsOnAppointmentsScalarWhereWithAggregatesInput | Prisma.TagsOnAppointmentsScalarWhereWithAggregatesInput[]
  OR?: Prisma.TagsOnAppointmentsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TagsOnAppointmentsScalarWhereWithAggregatesInput | Prisma.TagsOnAppointmentsScalarWhereWithAggregatesInput[]
  appointmentId?: Prisma.IntWithAggregatesFilter<"TagsOnAppointments"> | number
  tagId?: Prisma.IntWithAggregatesFilter<"TagsOnAppointments"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TagsOnAppointments"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TagsOnAppointments"> | Date | string
}

export type TagsOnAppointmentsCreateInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  appointment: Prisma.AppointmentCreateNestedOneWithoutTagsInput
  tag: Prisma.TagCreateNestedOneWithoutAppointmentTagsInput
}

export type TagsOnAppointmentsUncheckedCreateInput = {
  appointmentId: number
  tagId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TagsOnAppointmentsUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointment?: Prisma.AppointmentUpdateOneRequiredWithoutTagsNestedInput
  tag?: Prisma.TagUpdateOneRequiredWithoutAppointmentTagsNestedInput
}

export type TagsOnAppointmentsUncheckedUpdateInput = {
  appointmentId?: Prisma.IntFieldUpdateOperationsInput | number
  tagId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TagsOnAppointmentsCreateManyInput = {
  appointmentId: number
  tagId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TagsOnAppointmentsUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TagsOnAppointmentsUncheckedUpdateManyInput = {
  appointmentId?: Prisma.IntFieldUpdateOperationsInput | number
  tagId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TagsOnAppointmentsListRelationFilter = {
  every?: Prisma.TagsOnAppointmentsWhereInput
  some?: Prisma.TagsOnAppointmentsWhereInput
  none?: Prisma.TagsOnAppointmentsWhereInput
}

export type TagsOnAppointmentsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TagsOnAppointmentsAppointmentIdTagIdCompoundUniqueInput = {
  appointmentId: number
  tagId: number
}

export type TagsOnAppointmentsCountOrderByAggregateInput = {
  appointmentId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TagsOnAppointmentsAvgOrderByAggregateInput = {
  appointmentId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type TagsOnAppointmentsMaxOrderByAggregateInput = {
  appointmentId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TagsOnAppointmentsMinOrderByAggregateInput = {
  appointmentId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TagsOnAppointmentsSumOrderByAggregateInput = {
  appointmentId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type TagsOnAppointmentsCreateNestedManyWithoutAppointmentInput = {
  create?: Prisma.XOR<Prisma.TagsOnAppointmentsCreateWithoutAppointmentInput, Prisma.TagsOnAppointmentsUncheckedCreateWithoutAppointmentInput> | Prisma.TagsOnAppointmentsCreateWithoutAppointmentInput[] | Prisma.TagsOnAppointmentsUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.TagsOnAppointmentsCreateOrConnectWithoutAppointmentInput | Prisma.TagsOnAppointmentsCreateOrConnectWithoutAppointmentInput[]
  createMany?: Prisma.TagsOnAppointmentsCreateManyAppointmentInputEnvelope
  connect?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
}

export type TagsOnAppointmentsUncheckedCreateNestedManyWithoutAppointmentInput = {
  create?: Prisma.XOR<Prisma.TagsOnAppointmentsCreateWithoutAppointmentInput, Prisma.TagsOnAppointmentsUncheckedCreateWithoutAppointmentInput> | Prisma.TagsOnAppointmentsCreateWithoutAppointmentInput[] | Prisma.TagsOnAppointmentsUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.TagsOnAppointmentsCreateOrConnectWithoutAppointmentInput | Prisma.TagsOnAppointmentsCreateOrConnectWithoutAppointmentInput[]
  createMany?: Prisma.TagsOnAppointmentsCreateManyAppointmentInputEnvelope
  connect?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
}

export type TagsOnAppointmentsUpdateManyWithoutAppointmentNestedInput = {
  create?: Prisma.XOR<Prisma.TagsOnAppointmentsCreateWithoutAppointmentInput, Prisma.TagsOnAppointmentsUncheckedCreateWithoutAppointmentInput> | Prisma.TagsOnAppointmentsCreateWithoutAppointmentInput[] | Prisma.TagsOnAppointmentsUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.TagsOnAppointmentsCreateOrConnectWithoutAppointmentInput | Prisma.TagsOnAppointmentsCreateOrConnectWithoutAppointmentInput[]
  upsert?: Prisma.TagsOnAppointmentsUpsertWithWhereUniqueWithoutAppointmentInput | Prisma.TagsOnAppointmentsUpsertWithWhereUniqueWithoutAppointmentInput[]
  createMany?: Prisma.TagsOnAppointmentsCreateManyAppointmentInputEnvelope
  set?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
  disconnect?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
  delete?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
  connect?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
  update?: Prisma.TagsOnAppointmentsUpdateWithWhereUniqueWithoutAppointmentInput | Prisma.TagsOnAppointmentsUpdateWithWhereUniqueWithoutAppointmentInput[]
  updateMany?: Prisma.TagsOnAppointmentsUpdateManyWithWhereWithoutAppointmentInput | Prisma.TagsOnAppointmentsUpdateManyWithWhereWithoutAppointmentInput[]
  deleteMany?: Prisma.TagsOnAppointmentsScalarWhereInput | Prisma.TagsOnAppointmentsScalarWhereInput[]
}

export type TagsOnAppointmentsUncheckedUpdateManyWithoutAppointmentNestedInput = {
  create?: Prisma.XOR<Prisma.TagsOnAppointmentsCreateWithoutAppointmentInput, Prisma.TagsOnAppointmentsUncheckedCreateWithoutAppointmentInput> | Prisma.TagsOnAppointmentsCreateWithoutAppointmentInput[] | Prisma.TagsOnAppointmentsUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.TagsOnAppointmentsCreateOrConnectWithoutAppointmentInput | Prisma.TagsOnAppointmentsCreateOrConnectWithoutAppointmentInput[]
  upsert?: Prisma.TagsOnAppointmentsUpsertWithWhereUniqueWithoutAppointmentInput | Prisma.TagsOnAppointmentsUpsertWithWhereUniqueWithoutAppointmentInput[]
  createMany?: Prisma.TagsOnAppointmentsCreateManyAppointmentInputEnvelope
  set?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
  disconnect?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
  delete?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
  connect?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
  update?: Prisma.TagsOnAppointmentsUpdateWithWhereUniqueWithoutAppointmentInput | Prisma.TagsOnAppointmentsUpdateWithWhereUniqueWithoutAppointmentInput[]
  updateMany?: Prisma.TagsOnAppointmentsUpdateManyWithWhereWithoutAppointmentInput | Prisma.TagsOnAppointmentsUpdateManyWithWhereWithoutAppointmentInput[]
  deleteMany?: Prisma.TagsOnAppointmentsScalarWhereInput | Prisma.TagsOnAppointmentsScalarWhereInput[]
}

export type TagsOnAppointmentsCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.TagsOnAppointmentsCreateWithoutTagInput, Prisma.TagsOnAppointmentsUncheckedCreateWithoutTagInput> | Prisma.TagsOnAppointmentsCreateWithoutTagInput[] | Prisma.TagsOnAppointmentsUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.TagsOnAppointmentsCreateOrConnectWithoutTagInput | Prisma.TagsOnAppointmentsCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.TagsOnAppointmentsCreateManyTagInputEnvelope
  connect?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
}

export type TagsOnAppointmentsUncheckedCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.TagsOnAppointmentsCreateWithoutTagInput, Prisma.TagsOnAppointmentsUncheckedCreateWithoutTagInput> | Prisma.TagsOnAppointmentsCreateWithoutTagInput[] | Prisma.TagsOnAppointmentsUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.TagsOnAppointmentsCreateOrConnectWithoutTagInput | Prisma.TagsOnAppointmentsCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.TagsOnAppointmentsCreateManyTagInputEnvelope
  connect?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
}

export type TagsOnAppointmentsUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.TagsOnAppointmentsCreateWithoutTagInput, Prisma.TagsOnAppointmentsUncheckedCreateWithoutTagInput> | Prisma.TagsOnAppointmentsCreateWithoutTagInput[] | Prisma.TagsOnAppointmentsUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.TagsOnAppointmentsCreateOrConnectWithoutTagInput | Prisma.TagsOnAppointmentsCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.TagsOnAppointmentsUpsertWithWhereUniqueWithoutTagInput | Prisma.TagsOnAppointmentsUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.TagsOnAppointmentsCreateManyTagInputEnvelope
  set?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
  disconnect?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
  delete?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
  connect?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
  update?: Prisma.TagsOnAppointmentsUpdateWithWhereUniqueWithoutTagInput | Prisma.TagsOnAppointmentsUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.TagsOnAppointmentsUpdateManyWithWhereWithoutTagInput | Prisma.TagsOnAppointmentsUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.TagsOnAppointmentsScalarWhereInput | Prisma.TagsOnAppointmentsScalarWhereInput[]
}

export type TagsOnAppointmentsUncheckedUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.TagsOnAppointmentsCreateWithoutTagInput, Prisma.TagsOnAppointmentsUncheckedCreateWithoutTagInput> | Prisma.TagsOnAppointmentsCreateWithoutTagInput[] | Prisma.TagsOnAppointmentsUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.TagsOnAppointmentsCreateOrConnectWithoutTagInput | Prisma.TagsOnAppointmentsCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.TagsOnAppointmentsUpsertWithWhereUniqueWithoutTagInput | Prisma.TagsOnAppointmentsUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.TagsOnAppointmentsCreateManyTagInputEnvelope
  set?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
  disconnect?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
  delete?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
  connect?: Prisma.TagsOnAppointmentsWhereUniqueInput | Prisma.TagsOnAppointmentsWhereUniqueInput[]
  update?: Prisma.TagsOnAppointmentsUpdateWithWhereUniqueWithoutTagInput | Prisma.TagsOnAppointmentsUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.TagsOnAppointmentsUpdateManyWithWhereWithoutTagInput | Prisma.TagsOnAppointmentsUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.TagsOnAppointmentsScalarWhereInput | Prisma.TagsOnAppointmentsScalarWhereInput[]
}

export type TagsOnAppointmentsCreateWithoutAppointmentInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  tag: Prisma.TagCreateNestedOneWithoutAppointmentTagsInput
}

export type TagsOnAppointmentsUncheckedCreateWithoutAppointmentInput = {
  tagId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TagsOnAppointmentsCreateOrConnectWithoutAppointmentInput = {
  where: Prisma.TagsOnAppointmentsWhereUniqueInput
  create: Prisma.XOR<Prisma.TagsOnAppointmentsCreateWithoutAppointmentInput, Prisma.TagsOnAppointmentsUncheckedCreateWithoutAppointmentInput>
}

export type TagsOnAppointmentsCreateManyAppointmentInputEnvelope = {
  data: Prisma.TagsOnAppointmentsCreateManyAppointmentInput | Prisma.TagsOnAppointmentsCreateManyAppointmentInput[]
  skipDuplicates?: boolean
}

export type TagsOnAppointmentsUpsertWithWhereUniqueWithoutAppointmentInput = {
  where: Prisma.TagsOnAppointmentsWhereUniqueInput
  update: Prisma.XOR<Prisma.TagsOnAppointmentsUpdateWithoutAppointmentInput, Prisma.TagsOnAppointmentsUncheckedUpdateWithoutAppointmentInput>
  create: Prisma.XOR<Prisma.TagsOnAppointmentsCreateWithoutAppointmentInput, Prisma.TagsOnAppointmentsUncheckedCreateWithoutAppointmentInput>
}

export type TagsOnAppointmentsUpdateWithWhereUniqueWithoutAppointmentInput = {
  where: Prisma.TagsOnAppointmentsWhereUniqueInput
  data: Prisma.XOR<Prisma.TagsOnAppointmentsUpdateWithoutAppointmentInput, Prisma.TagsOnAppointmentsUncheckedUpdateWithoutAppointmentInput>
}

export type TagsOnAppointmentsUpdateManyWithWhereWithoutAppointmentInput = {
  where: Prisma.TagsOnAppointmentsScalarWhereInput
  data: Prisma.XOR<Prisma.TagsOnAppointmentsUpdateManyMutationInput, Prisma.TagsOnAppointmentsUncheckedUpdateManyWithoutAppointmentInput>
}

export type TagsOnAppointmentsScalarWhereInput = {
  AND?: Prisma.TagsOnAppointmentsScalarWhereInput | Prisma.TagsOnAppointmentsScalarWhereInput[]
  OR?: Prisma.TagsOnAppointmentsScalarWhereInput[]
  NOT?: Prisma.TagsOnAppointmentsScalarWhereInput | Prisma.TagsOnAppointmentsScalarWhereInput[]
  appointmentId?: Prisma.IntFilter<"TagsOnAppointments"> | number
  tagId?: Prisma.IntFilter<"TagsOnAppointments"> | number
  createdAt?: Prisma.DateTimeFilter<"TagsOnAppointments"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TagsOnAppointments"> | Date | string
}

export type TagsOnAppointmentsCreateWithoutTagInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  appointment: Prisma.AppointmentCreateNestedOneWithoutTagsInput
}

export type TagsOnAppointmentsUncheckedCreateWithoutTagInput = {
  appointmentId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TagsOnAppointmentsCreateOrConnectWithoutTagInput = {
  where: Prisma.TagsOnAppointmentsWhereUniqueInput
  create: Prisma.XOR<Prisma.TagsOnAppointmentsCreateWithoutTagInput, Prisma.TagsOnAppointmentsUncheckedCreateWithoutTagInput>
}

export type TagsOnAppointmentsCreateManyTagInputEnvelope = {
  data: Prisma.TagsOnAppointmentsCreateManyTagInput | Prisma.TagsOnAppointmentsCreateManyTagInput[]
  skipDuplicates?: boolean
}

export type TagsOnAppointmentsUpsertWithWhereUniqueWithoutTagInput = {
  where: Prisma.TagsOnAppointmentsWhereUniqueInput
  update: Prisma.XOR<Prisma.TagsOnAppointmentsUpdateWithoutTagInput, Prisma.TagsOnAppointmentsUncheckedUpdateWithoutTagInput>
  create: Prisma.XOR<Prisma.TagsOnAppointmentsCreateWithoutTagInput, Prisma.TagsOnAppointmentsUncheckedCreateWithoutTagInput>
}

export type TagsOnAppointmentsUpdateWithWhereUniqueWithoutTagInput = {
  where: Prisma.TagsOnAppointmentsWhereUniqueInput
  data: Prisma.XOR<Prisma.TagsOnAppointmentsUpdateWithoutTagInput, Prisma.TagsOnAppointmentsUncheckedUpdateWithoutTagInput>
}

export type TagsOnAppointmentsUpdateManyWithWhereWithoutTagInput = {
  where: Prisma.TagsOnAppointmentsScalarWhereInput
  data: Prisma.XOR<Prisma.TagsOnAppointmentsUpdateManyMutationInput, Prisma.TagsOnAppointmentsUncheckedUpdateManyWithoutTagInput>
}

export type TagsOnAppointmentsCreateManyAppointmentInput = {
  tagId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TagsOnAppointmentsUpdateWithoutAppointmentInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tag?: Prisma.TagUpdateOneRequiredWithoutAppointmentTagsNestedInput
}

export type TagsOnAppointmentsUncheckedUpdateWithoutAppointmentInput = {
  tagId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TagsOnAppointmentsUncheckedUpdateManyWithoutAppointmentInput = {
  tagId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TagsOnAppointmentsCreateManyTagInput = {
  appointmentId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TagsOnAppointmentsUpdateWithoutTagInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointment?: Prisma.AppointmentUpdateOneRequiredWithoutTagsNestedInput
}

export type TagsOnAppointmentsUncheckedUpdateWithoutTagInput = {
  appointmentId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TagsOnAppointmentsUncheckedUpdateManyWithoutTagInput = {
  appointmentId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TagsOnAppointmentsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  appointmentId?: boolean
  tagId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tagsOnAppointments"]>



export type TagsOnAppointmentsSelectScalar = {
  appointmentId?: boolean
  tagId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TagsOnAppointmentsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"appointmentId" | "tagId" | "createdAt" | "updatedAt", ExtArgs["result"]["tagsOnAppointments"]>
export type TagsOnAppointmentsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}

export type $TagsOnAppointmentsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TagsOnAppointments"
  objects: {
    appointment: Prisma.$AppointmentPayload<ExtArgs>
    tag: Prisma.$TagPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    appointmentId: number
    tagId: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["tagsOnAppointments"]>
  composites: {}
}

export type TagsOnAppointmentsGetPayload<S extends boolean | null | undefined | TagsOnAppointmentsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TagsOnAppointmentsPayload, S>

export type TagsOnAppointmentsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TagsOnAppointmentsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TagsOnAppointmentsCountAggregateInputType | true
  }

export interface TagsOnAppointmentsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TagsOnAppointments'], meta: { name: 'TagsOnAppointments' } }
  /**
   * Find zero or one TagsOnAppointments that matches the filter.
   * @param {TagsOnAppointmentsFindUniqueArgs} args - Arguments to find a TagsOnAppointments
   * @example
   * // Get one TagsOnAppointments
   * const tagsOnAppointments = await prisma.tagsOnAppointments.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TagsOnAppointmentsFindUniqueArgs>(args: Prisma.SelectSubset<T, TagsOnAppointmentsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TagsOnAppointmentsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnAppointmentsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TagsOnAppointments that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TagsOnAppointmentsFindUniqueOrThrowArgs} args - Arguments to find a TagsOnAppointments
   * @example
   * // Get one TagsOnAppointments
   * const tagsOnAppointments = await prisma.tagsOnAppointments.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TagsOnAppointmentsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TagsOnAppointmentsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TagsOnAppointmentsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnAppointmentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TagsOnAppointments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnAppointmentsFindFirstArgs} args - Arguments to find a TagsOnAppointments
   * @example
   * // Get one TagsOnAppointments
   * const tagsOnAppointments = await prisma.tagsOnAppointments.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TagsOnAppointmentsFindFirstArgs>(args?: Prisma.SelectSubset<T, TagsOnAppointmentsFindFirstArgs<ExtArgs>>): Prisma.Prisma__TagsOnAppointmentsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnAppointmentsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TagsOnAppointments that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnAppointmentsFindFirstOrThrowArgs} args - Arguments to find a TagsOnAppointments
   * @example
   * // Get one TagsOnAppointments
   * const tagsOnAppointments = await prisma.tagsOnAppointments.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TagsOnAppointmentsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TagsOnAppointmentsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TagsOnAppointmentsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnAppointmentsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TagsOnAppointments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnAppointmentsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TagsOnAppointments
   * const tagsOnAppointments = await prisma.tagsOnAppointments.findMany()
   * 
   * // Get first 10 TagsOnAppointments
   * const tagsOnAppointments = await prisma.tagsOnAppointments.findMany({ take: 10 })
   * 
   * // Only select the `appointmentId`
   * const tagsOnAppointmentsWithAppointmentIdOnly = await prisma.tagsOnAppointments.findMany({ select: { appointmentId: true } })
   * 
   */
  findMany<T extends TagsOnAppointmentsFindManyArgs>(args?: Prisma.SelectSubset<T, TagsOnAppointmentsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TagsOnAppointmentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TagsOnAppointments.
   * @param {TagsOnAppointmentsCreateArgs} args - Arguments to create a TagsOnAppointments.
   * @example
   * // Create one TagsOnAppointments
   * const TagsOnAppointments = await prisma.tagsOnAppointments.create({
   *   data: {
   *     // ... data to create a TagsOnAppointments
   *   }
   * })
   * 
   */
  create<T extends TagsOnAppointmentsCreateArgs>(args: Prisma.SelectSubset<T, TagsOnAppointmentsCreateArgs<ExtArgs>>): Prisma.Prisma__TagsOnAppointmentsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnAppointmentsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TagsOnAppointments.
   * @param {TagsOnAppointmentsCreateManyArgs} args - Arguments to create many TagsOnAppointments.
   * @example
   * // Create many TagsOnAppointments
   * const tagsOnAppointments = await prisma.tagsOnAppointments.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TagsOnAppointmentsCreateManyArgs>(args?: Prisma.SelectSubset<T, TagsOnAppointmentsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a TagsOnAppointments.
   * @param {TagsOnAppointmentsDeleteArgs} args - Arguments to delete one TagsOnAppointments.
   * @example
   * // Delete one TagsOnAppointments
   * const TagsOnAppointments = await prisma.tagsOnAppointments.delete({
   *   where: {
   *     // ... filter to delete one TagsOnAppointments
   *   }
   * })
   * 
   */
  delete<T extends TagsOnAppointmentsDeleteArgs>(args: Prisma.SelectSubset<T, TagsOnAppointmentsDeleteArgs<ExtArgs>>): Prisma.Prisma__TagsOnAppointmentsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnAppointmentsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TagsOnAppointments.
   * @param {TagsOnAppointmentsUpdateArgs} args - Arguments to update one TagsOnAppointments.
   * @example
   * // Update one TagsOnAppointments
   * const tagsOnAppointments = await prisma.tagsOnAppointments.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TagsOnAppointmentsUpdateArgs>(args: Prisma.SelectSubset<T, TagsOnAppointmentsUpdateArgs<ExtArgs>>): Prisma.Prisma__TagsOnAppointmentsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnAppointmentsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TagsOnAppointments.
   * @param {TagsOnAppointmentsDeleteManyArgs} args - Arguments to filter TagsOnAppointments to delete.
   * @example
   * // Delete a few TagsOnAppointments
   * const { count } = await prisma.tagsOnAppointments.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TagsOnAppointmentsDeleteManyArgs>(args?: Prisma.SelectSubset<T, TagsOnAppointmentsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TagsOnAppointments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnAppointmentsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TagsOnAppointments
   * const tagsOnAppointments = await prisma.tagsOnAppointments.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TagsOnAppointmentsUpdateManyArgs>(args: Prisma.SelectSubset<T, TagsOnAppointmentsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one TagsOnAppointments.
   * @param {TagsOnAppointmentsUpsertArgs} args - Arguments to update or create a TagsOnAppointments.
   * @example
   * // Update or create a TagsOnAppointments
   * const tagsOnAppointments = await prisma.tagsOnAppointments.upsert({
   *   create: {
   *     // ... data to create a TagsOnAppointments
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TagsOnAppointments we want to update
   *   }
   * })
   */
  upsert<T extends TagsOnAppointmentsUpsertArgs>(args: Prisma.SelectSubset<T, TagsOnAppointmentsUpsertArgs<ExtArgs>>): Prisma.Prisma__TagsOnAppointmentsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnAppointmentsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TagsOnAppointments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnAppointmentsCountArgs} args - Arguments to filter TagsOnAppointments to count.
   * @example
   * // Count the number of TagsOnAppointments
   * const count = await prisma.tagsOnAppointments.count({
   *   where: {
   *     // ... the filter for the TagsOnAppointments we want to count
   *   }
   * })
  **/
  count<T extends TagsOnAppointmentsCountArgs>(
    args?: Prisma.Subset<T, TagsOnAppointmentsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TagsOnAppointmentsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TagsOnAppointments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnAppointmentsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TagsOnAppointmentsAggregateArgs>(args: Prisma.Subset<T, TagsOnAppointmentsAggregateArgs>): Prisma.PrismaPromise<GetTagsOnAppointmentsAggregateType<T>>

  /**
   * Group by TagsOnAppointments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnAppointmentsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TagsOnAppointmentsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TagsOnAppointmentsGroupByArgs['orderBy'] }
      : { orderBy?: TagsOnAppointmentsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TagsOnAppointmentsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTagsOnAppointmentsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TagsOnAppointments model
 */
readonly fields: TagsOnAppointmentsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TagsOnAppointments.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TagsOnAppointmentsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  appointment<T extends Prisma.AppointmentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppointmentDefaultArgs<ExtArgs>>): Prisma.Prisma__AppointmentClient<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  tag<T extends Prisma.TagDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TagDefaultArgs<ExtArgs>>): Prisma.Prisma__TagClient<runtime.Types.Result.GetResult<Prisma.$TagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TagsOnAppointments model
 */
export interface TagsOnAppointmentsFieldRefs {
  readonly appointmentId: Prisma.FieldRef<"TagsOnAppointments", 'Int'>
  readonly tagId: Prisma.FieldRef<"TagsOnAppointments", 'Int'>
  readonly createdAt: Prisma.FieldRef<"TagsOnAppointments", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TagsOnAppointments", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TagsOnAppointments findUnique
 */
export type TagsOnAppointmentsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnAppointments
   */
  select?: Prisma.TagsOnAppointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnAppointments
   */
  omit?: Prisma.TagsOnAppointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnAppointmentsInclude<ExtArgs> | null
  /**
   * Filter, which TagsOnAppointments to fetch.
   */
  where: Prisma.TagsOnAppointmentsWhereUniqueInput
}

/**
 * TagsOnAppointments findUniqueOrThrow
 */
export type TagsOnAppointmentsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnAppointments
   */
  select?: Prisma.TagsOnAppointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnAppointments
   */
  omit?: Prisma.TagsOnAppointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnAppointmentsInclude<ExtArgs> | null
  /**
   * Filter, which TagsOnAppointments to fetch.
   */
  where: Prisma.TagsOnAppointmentsWhereUniqueInput
}

/**
 * TagsOnAppointments findFirst
 */
export type TagsOnAppointmentsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnAppointments
   */
  select?: Prisma.TagsOnAppointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnAppointments
   */
  omit?: Prisma.TagsOnAppointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnAppointmentsInclude<ExtArgs> | null
  /**
   * Filter, which TagsOnAppointments to fetch.
   */
  where?: Prisma.TagsOnAppointmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagsOnAppointments to fetch.
   */
  orderBy?: Prisma.TagsOnAppointmentsOrderByWithRelationInput | Prisma.TagsOnAppointmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TagsOnAppointments.
   */
  cursor?: Prisma.TagsOnAppointmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagsOnAppointments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagsOnAppointments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TagsOnAppointments.
   */
  distinct?: Prisma.TagsOnAppointmentsScalarFieldEnum | Prisma.TagsOnAppointmentsScalarFieldEnum[]
}

/**
 * TagsOnAppointments findFirstOrThrow
 */
export type TagsOnAppointmentsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnAppointments
   */
  select?: Prisma.TagsOnAppointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnAppointments
   */
  omit?: Prisma.TagsOnAppointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnAppointmentsInclude<ExtArgs> | null
  /**
   * Filter, which TagsOnAppointments to fetch.
   */
  where?: Prisma.TagsOnAppointmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagsOnAppointments to fetch.
   */
  orderBy?: Prisma.TagsOnAppointmentsOrderByWithRelationInput | Prisma.TagsOnAppointmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TagsOnAppointments.
   */
  cursor?: Prisma.TagsOnAppointmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagsOnAppointments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagsOnAppointments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TagsOnAppointments.
   */
  distinct?: Prisma.TagsOnAppointmentsScalarFieldEnum | Prisma.TagsOnAppointmentsScalarFieldEnum[]
}

/**
 * TagsOnAppointments findMany
 */
export type TagsOnAppointmentsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnAppointments
   */
  select?: Prisma.TagsOnAppointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnAppointments
   */
  omit?: Prisma.TagsOnAppointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnAppointmentsInclude<ExtArgs> | null
  /**
   * Filter, which TagsOnAppointments to fetch.
   */
  where?: Prisma.TagsOnAppointmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagsOnAppointments to fetch.
   */
  orderBy?: Prisma.TagsOnAppointmentsOrderByWithRelationInput | Prisma.TagsOnAppointmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TagsOnAppointments.
   */
  cursor?: Prisma.TagsOnAppointmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagsOnAppointments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagsOnAppointments.
   */
  skip?: number
  distinct?: Prisma.TagsOnAppointmentsScalarFieldEnum | Prisma.TagsOnAppointmentsScalarFieldEnum[]
}

/**
 * TagsOnAppointments create
 */
export type TagsOnAppointmentsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnAppointments
   */
  select?: Prisma.TagsOnAppointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnAppointments
   */
  omit?: Prisma.TagsOnAppointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnAppointmentsInclude<ExtArgs> | null
  /**
   * The data needed to create a TagsOnAppointments.
   */
  data: Prisma.XOR<Prisma.TagsOnAppointmentsCreateInput, Prisma.TagsOnAppointmentsUncheckedCreateInput>
}

/**
 * TagsOnAppointments createMany
 */
export type TagsOnAppointmentsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TagsOnAppointments.
   */
  data: Prisma.TagsOnAppointmentsCreateManyInput | Prisma.TagsOnAppointmentsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TagsOnAppointments update
 */
export type TagsOnAppointmentsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnAppointments
   */
  select?: Prisma.TagsOnAppointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnAppointments
   */
  omit?: Prisma.TagsOnAppointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnAppointmentsInclude<ExtArgs> | null
  /**
   * The data needed to update a TagsOnAppointments.
   */
  data: Prisma.XOR<Prisma.TagsOnAppointmentsUpdateInput, Prisma.TagsOnAppointmentsUncheckedUpdateInput>
  /**
   * Choose, which TagsOnAppointments to update.
   */
  where: Prisma.TagsOnAppointmentsWhereUniqueInput
}

/**
 * TagsOnAppointments updateMany
 */
export type TagsOnAppointmentsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TagsOnAppointments.
   */
  data: Prisma.XOR<Prisma.TagsOnAppointmentsUpdateManyMutationInput, Prisma.TagsOnAppointmentsUncheckedUpdateManyInput>
  /**
   * Filter which TagsOnAppointments to update
   */
  where?: Prisma.TagsOnAppointmentsWhereInput
  /**
   * Limit how many TagsOnAppointments to update.
   */
  limit?: number
}

/**
 * TagsOnAppointments upsert
 */
export type TagsOnAppointmentsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnAppointments
   */
  select?: Prisma.TagsOnAppointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnAppointments
   */
  omit?: Prisma.TagsOnAppointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnAppointmentsInclude<ExtArgs> | null
  /**
   * The filter to search for the TagsOnAppointments to update in case it exists.
   */
  where: Prisma.TagsOnAppointmentsWhereUniqueInput
  /**
   * In case the TagsOnAppointments found by the `where` argument doesn't exist, create a new TagsOnAppointments with this data.
   */
  create: Prisma.XOR<Prisma.TagsOnAppointmentsCreateInput, Prisma.TagsOnAppointmentsUncheckedCreateInput>
  /**
   * In case the TagsOnAppointments was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TagsOnAppointmentsUpdateInput, Prisma.TagsOnAppointmentsUncheckedUpdateInput>
}

/**
 * TagsOnAppointments delete
 */
export type TagsOnAppointmentsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnAppointments
   */
  select?: Prisma.TagsOnAppointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnAppointments
   */
  omit?: Prisma.TagsOnAppointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnAppointmentsInclude<ExtArgs> | null
  /**
   * Filter which TagsOnAppointments to delete.
   */
  where: Prisma.TagsOnAppointmentsWhereUniqueInput
}

/**
 * TagsOnAppointments deleteMany
 */
export type TagsOnAppointmentsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TagsOnAppointments to delete
   */
  where?: Prisma.TagsOnAppointmentsWhereInput
  /**
   * Limit how many TagsOnAppointments to delete.
   */
  limit?: number
}

/**
 * TagsOnAppointments without action
 */
export type TagsOnAppointmentsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnAppointments
   */
  select?: Prisma.TagsOnAppointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnAppointments
   */
  omit?: Prisma.TagsOnAppointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnAppointmentsInclude<ExtArgs> | null
}
