
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Appointment: 'Appointment',
  Tag: 'Tag',
  DefaultTag: 'DefaultTag',
  Participant: 'Participant',
  ParticipantMark: 'ParticipantMark',
  User: 'User',
  LoginProviderCode: 'LoginProviderCode'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AppointmentScalarFieldEnum = {
  id: 'id',
  nonce: 'nonce',
  name: 'name',
  startDate: 'startDate',
  endDate: 'endDate',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AppointmentScalarFieldEnum = (typeof AppointmentScalarFieldEnum)[keyof typeof AppointmentScalarFieldEnum]


export const TagScalarFieldEnum = {
  id: 'id',
  name: 'name',
  nameSearch: 'nameSearch'
} as const

export type TagScalarFieldEnum = (typeof TagScalarFieldEnum)[keyof typeof TagScalarFieldEnum]


export const DefaultTagScalarFieldEnum = {
  id: 'id',
  tagId: 'tagId'
} as const

export type DefaultTagScalarFieldEnum = (typeof DefaultTagScalarFieldEnum)[keyof typeof DefaultTagScalarFieldEnum]


export const ParticipantScalarFieldEnum = {
  id: 'id',
  name: 'name',
  appointmentId: 'appointmentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ParticipantScalarFieldEnum = (typeof ParticipantScalarFieldEnum)[keyof typeof ParticipantScalarFieldEnum]


export const ParticipantMarkScalarFieldEnum = {
  participantId: 'participantId',
  tagId: 'tagId',
  calendarDate: 'calendarDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ParticipantMarkScalarFieldEnum = (typeof ParticipantMarkScalarFieldEnum)[keyof typeof ParticipantMarkScalarFieldEnum]


export const UserScalarFieldEnum = {
  userId: 'userId',
  privilege: 'privilege'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const LoginProviderCodeScalarFieldEnum = {
  userId: 'userId',
  code: 'code'
} as const

export type LoginProviderCodeScalarFieldEnum = (typeof LoginProviderCodeScalarFieldEnum)[keyof typeof LoginProviderCodeScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const AppointmentOrderByRelevanceFieldEnum = {
  name: 'name'
} as const

export type AppointmentOrderByRelevanceFieldEnum = (typeof AppointmentOrderByRelevanceFieldEnum)[keyof typeof AppointmentOrderByRelevanceFieldEnum]


export const TagOrderByRelevanceFieldEnum = {
  name: 'name',
  nameSearch: 'nameSearch'
} as const

export type TagOrderByRelevanceFieldEnum = (typeof TagOrderByRelevanceFieldEnum)[keyof typeof TagOrderByRelevanceFieldEnum]


export const ParticipantOrderByRelevanceFieldEnum = {
  name: 'name'
} as const

export type ParticipantOrderByRelevanceFieldEnum = (typeof ParticipantOrderByRelevanceFieldEnum)[keyof typeof ParticipantOrderByRelevanceFieldEnum]

